### ISSUE TITLE
Sprint 1 - Team 9 Task Ticket 1: Chap 1 Dialogue & Clues

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#10]
# **Description**
**Task:** [NPC Relationship & Clues](#10).
**Feature:** [Communication with NPC](#9)

Since we are at the very beginning of building up the background of this game, the very first task is relying on the general storyline. Based on it, we could start our work and figure out the relationship and any potential clues that we could added on the game while building the dialogues between NPC and players. We will generally make a relationship map with each NPC's background stories and the main character (player)'s background setting. Once we figured out this, we could develop further to set up different lines lead to either win or lose.

# **Dependencies**
- [x] character design info (#13 #7)
- [x] storyline/general background (#7 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] discuss some of the chapter details with Team 5
- [x] write a draft dialogue for Chap 1
- [x] discuss with other related teams & update the content
 
**Completion Deadline:** Aug. 20
- [x] discuss some of the chapter details with Team 5 (anytime needed)
- [x] write a draft dialogue for Chap 1 (Aug. 20-24).
- [x] discuss with other related teams & update the content (Aug. 24-25)

 
# **Documentation**
- [Feature: NPC Communication Play Script](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-Communication--Play-Script)

 
# **Member**
- Jingyi Li (@AlynnLi ) (Jingyi Li)
- Yifei LIu (@liu8868 ) (Yifei Liu)
- Yufan Chen (@snakefen) (Yufan)
- Junyu Zhu (@45190331) (Junyu_Zhu)

**Comment by snakefen** [comment]
> # **Description**
> **Task:** [NPC Relationship & Clues](#10). **Feature:** [Communication with NPC](#9)
> 
> Since we are at the very beginning of building up the background of this game, the very first task is relying on the general storyline. Based on it, we could start our work and figure out the relationship and any potential clues that we could added on the game while building the dialogues between NPC and players. We will generally make a relationship map with each NPC's background stories and the main character (player)'s background setting. Once we figured out this, we could develop further to set up different lines lead to either win or lose.
> 
> # **Dependencies**
> * [ ]  storyline/general background ([Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7](https://github.com/UQdeco2800/2022-ext-studio-1/issues/7) )
> * [ ]  character design info (#team 1)
> 
> # **Milestones**
> List of steps that need to be completed for this task.
> 
> * [ ]  wait for team 5 to get the whole general storyline (whenever team 5 is ready)
> * [ ]  figure out NPC relationships (Aug. 18?)
> * [ ]  make up clues (Aug. 20?)
> 
> **Completion Deadline:** Aug. 20
> 
> * [ ]  figure out NPC relationships according to team5's storyline (Aug. 18).
> * [ ]  based on the relationships, make up some possible clues, discuss this with team5 (Aug. 20).
> 
> # **Documentation**
> * [Main description of feature](../wiki/Feature)
> * [JavaDoc](JavaDoc/Location/Package/Class)
> * ...
> 
> # **Member**
> * Jingyi Li (@AlynnLi ) (Jingyi Li)
> * Yifei LIu (@liu8868 ) (Yifei Liu)
> * Yufan Chen (@snakefen) (Yufan)
> * Junyu Zhu (@45190331) (Junyu_Zhu)

**Comment by snakefen** [comment]
> # **Description**
> **Task:** [NPC Relationship & Clues](#10). **Feature:** [Communication with NPC](#9)
> 
> Since we are at the very beginning of building up the background of this game, the very first task is relying on the general storyline. Based on it, we could start our work and figure out the relationship and any potential clues that we could added on the game while building the dialogues between NPC and players. We will generally make a relationship map with each NPC's background stories and the main character (player)'s background setting. Once we figured out this, we could develop further to set up different lines lead to either win or lose.
> 
> # **Dependencies**
> * [ ]  storyline/general background ([Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7](https://github.com/UQdeco2800/2022-ext-studio-1/issues/7) )
> * [ ]  character design info (#team 1)
> 
> # **Milestones**
> List of steps that need to be completed for this task.
> 
> * [ ]  wait for team 5 to get the whole general storyline (whenever team 5 is ready)
> * [ ]  figure out NPC relationships (Aug. 18?)
> * [ ]  make up clues (Aug. 20?)
> 
> **Completion Deadline:** Aug. 20
> 
> * [ ]  figure out NPC relationships according to team5's storyline (Aug. 18).
> * [ ]  based on the relationships, make up some possible clues, discuss this with team5 (Aug. 20).
> 
> # **Documentation**
> * [Main description of feature](../wiki/Feature)
> * [JavaDoc](JavaDoc/Location/Package/Class)
> * ...
> 
> # **Member**
> * Jingyi Li (@AlynnLi ) (Jingyi Li)
> * Yifei LIu (@liu8868 ) (Yifei Liu)
> * Yufan Chen (@snakefen) (Yufan)
> * Junyu Zhu (@45190331) (Junyu_Zhu)

**Comment by snakefen** [comment]
> # **Description**
> **Task:** [NPC Relationship & Clues](#10). **Feature:** [Communication with NPC](#9)
> 
> Since we are at the very beginning of building up the background of this game, the very first task is relying on the general storyline. Based on it, we could start our work and figure out the relationship and any potential clues that we could added on the game while building the dialogues between NPC and players. We will generally make a relationship map with each NPC's background stories and the main character (player)'s background setting. Once we figured out this, we could develop further to set up different lines lead to either win or lose.
> 
> # **Dependencies**
> * [ ]  storyline/general background ([Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7](https://github.com/UQdeco2800/2022-ext-studio-1/issues/7) )
> * [ ]  character design info (#team 1)
> 
> # **Milestones**
> List of steps that need to be completed for this task.
> 
> * [ ]  wait for team 5 to get the whole general storyline (whenever team 5 is ready)
> * [ ]  figure out NPC relationships (Aug. 18?)
> * [ ]  make up clues (Aug. 20?)
> 
> **Completion Deadline:** Aug. 20
> 
> * [ ]  figure out NPC relationships according to team5's storyline (Aug. 18).
> * [ ]  based on the relationships, make up some possible clues, discuss this with team5 (Aug. 20).
> 
> # **Documentation**
> * [Main description of feature](../wiki/Feature)
> * [JavaDoc](JavaDoc/Location/Package/Class)
> * ...
> 
> # **Member**
> * Jingyi Li (@AlynnLi ) (Jingyi Li)
> * Yifei LIu (@liu8868 ) (Yifei Liu)
> * Yufan Chen (@snakefen) (Yufan)
> * Junyu Zhu (@45190331) (Junyu_Zhu)

**Comment by snakefen** [comment]
> # **Description**
> **Task:** [NPC Relationship & Clues](#10). **Feature:** [Communication with NPC](#9)
> 
> Since we are at the very beginning of building up the background of this game, the very first task is relying on the general storyline. Based on it, we could start our work and figure out the relationship and any potential clues that we could added on the game while building the dialogues between NPC and players. We will generally make a relationship map with each NPC's background stories and the main character (player)'s background setting. Once we figured out this, we could develop further to set up different lines lead to either win or lose.
> 
> # **Dependencies**
> * [ ]  storyline/general background ([Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7](https://github.com/UQdeco2800/2022-ext-studio-1/issues/7) )
> * [ ]  character design info (#team 1)
> 
> # **Milestones**
> List of steps that need to be completed for this task.
> 
> * [ ]  wait for team 5 to get the whole general storyline (whenever team 5 is ready)
> * [ ]  figure out NPC relationships (Aug. 18?)
> * [ ]  make up clues (Aug. 20?)
> 
> **Completion Deadline:** Aug. 20
> 
> * [ ]  figure out NPC relationships according to team5's storyline (Aug. 18).
> * [ ]  based on the relationships, make up some possible clues, discuss this with team5 (Aug. 20).
> 
> # **Documentation**
> * [Main description of feature](../wiki/Feature)
> * [JavaDoc](JavaDoc/Location/Package/Class)
> * ...
> 
> # **Member**
> * Jingyi Li (@AlynnLi ) (Jingyi Li)
> * Yifei LIu (@liu8868 ) (Yifei Liu)
> * Yufan Chen (@snakefen) (Yufan)
> * Junyu Zhu (@45190331) (Junyu_Zhu)

**Comment by snakefen** [comment]
> # **Description**
> **Task:** [NPC Relationship & Clues](#10). **Feature:** [Communication with NPC](#9)
> 
> Since we are at the very beginning of building up the background of this game, the very first task is relying on the general storyline. Based on it, we could start our work and figure out the relationship and any potential clues that we could added on the game while building the dialogues between NPC and players. We will generally make a relationship map with each NPC's background stories and the main character (player)'s background setting. Once we figured out this, we could develop further to set up different lines lead to either win or lose.
> 
> # **Dependencies**
> * [ ]  storyline/general background ([Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7](https://github.com/UQdeco2800/2022-ext-studio-1/issues/7) )
> * [ ]  character design info (#team 1)
> 
> # **Milestones**
> List of steps that need to be completed for this task.
> 
> * [ ]  wait for team 5 to get the whole general storyline (whenever team 5 is ready)
> * [ ]  figure out NPC relationships (Aug. 18?)
> * [ ]  make up clues (Aug. 20?)
> 
> **Completion Deadline:** Aug. 20
> 
> * [ ]  figure out NPC relationships according to team5's storyline (Aug. 18).
> * [ ]  based on the relationships, make up some possible clues, discuss this with team5 (Aug. 20).
> 
> # **Documentation**
> * [Main description of feature](../wiki/Feature)
> * [JavaDoc](JavaDoc/Location/Package/Class)
> * ...
> 
> # **Member**
> * Jingyi Li (@AlynnLi ) (Jingyi Li)
> * Yifei LIu (@liu8868 ) (Yifei Liu)
> * Yufan Chen (@snakefan) (Yufan)
> * Junyu Zhu (@45190331) (Junyu_Zhu)

**Comment by snakefen** [comment]
> # **Description**
> **Task:** [NPC Relationship & Clues](#10). **Feature:** [Communication with NPC](#9)
> 
> Since we are at the very beginning of building up the background of this game, the very first task is relying on the general storyline. Based on it, we could start our work and figure out the relationship and any potential clues that we could added on the game while building the dialogues between NPC and players. We will generally make a relationship map with each NPC's background stories and the main character (player)'s background setting. Once we figured out this, we could develop further to set up different lines lead to either win or lose.
> 
> # **Dependencies**
> * [ ]  storyline/general background ([Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7](https://github.com/UQdeco2800/2022-ext-studio-1/issues/7) )
> * [ ]  character design info (#team 1)
> 
> # **Milestones**
> List of steps that need to be completed for this task.
> 
> * [ ]  wait for team 5 to get the whole general storyline (whenever team 5 is ready)
> * [ ]  figure out NPC relationships (Aug. 18?)
> * [ ]  make up clues (Aug. 20?)
> 
> **Completion Deadline:** Aug. 20
> 
> * [ ]  figure out NPC relationships according to team5's storyline (Aug. 18).
> * [ ]  based on the relationships, make up some possible clues, discuss this with team5 (Aug. 20).
> 
> # **Documentation**
> * [Main description of feature](../wiki/Feature)
> * [JavaDoc](JavaDoc/Location/Package/Class)
> * ...
> 
> # **Member**
> * Jingyi Li (@AlynnLi ) (Jingyi Li)
> * Yifei LIu (@liu8868 ) (Yifei Liu)
> * Yufan Chen (@snakefen) (Yufan)
> * Junyu Zhu (@45190331) (Junyu_Zhu)

**Comment by AlynnLi** [comment]
Finished ticket
