### ISSUE TITLE
Sprint 1 - Team 2 Feature Ticket : Achievement System

### ISSUE THREAD

**Issue by Kai9613** [UQdeco2800/2022-ext-studio-1#11]
# **Description**
Designing the game's achievement system. As the player progresses in the game, when certain conditions are met, the achievement system will prompt the player that the achievement has been achieved. The player's achievement completion status will be summarized in the achievement interface.

The current concept includes two kinds of achievements, one is the collection achievement and the other is the social achievement.

## SubFeature/component
 - Achievement conditions: achieve certain conditions as an achievement
 - Achievement UI design: A list of trophies for achievement
 - Outcome: Display the achievement information on the achievement page

## **Examples**
- **Achievement**: Congratulations! You have collected all of the items!
# **Dependencies**
- Game story completion status Team 5 #7 
- Item collection status Team 8 #18 
- Communication status with NPC Team 9 #9 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Design different Achievement, and conditions for achieving.  (Aug. 20)
- [x] Design low/medium- fidelity prototype, with basic UI and UX (Aug. 23)
- [x] Finish coding conditions of achievement. (Aug. 26)
- [x] Finish coding basic UI Design (Aug. 28)
- [x] User testing & evaluation (Aug. 29)

**Completion Deadline:** Aug. 30

# **Extras (optional)**

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Xinkai Tang (@Kai9613)
- Zihao Xia (@zihao-xia)
- Minrui Xu (@wsxmr1234)
- Qicheng Chen (@Wayneecc)
