### ISSUE TITLE
Sprint 3 - Team 2 Feature Ticket:  Player interaction with Npc + aligning with storyline

### ISSUE THREAD

**Issue by zihao-xia** [UQdeco2800/2022-ext-studio-1#117]
# **Description**
Implement player interaction with Npc & aligning with storyline. NPCs need to be placed on the actual maps of the corresponding chapters, so that the player can interact with them to get clue items or enter the other maps. The detailed interactions with NPCs include character dialogues, exchange of items and clues, unlocking of other maps and chapters, etc.

# **Dependencies**
- actual game map design for the village Team 5
- actual clues/pickables relevant to the storyline Team 6
- collecting games inside each chapter Team 9

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Design a Portal NPC to go back to the previous maps  (Sep. 18)
- [ ] Place the NPCs on the maps of the corresponding chapters (Sep. 23)
- [ ] Determine and implement the conditions for clues to the player (Sep. 30)
- [ ] Implement interaction with NPC (Oct. 4)

**Completion Deadline:** Oct. 5

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Zihao Xia (@zihao-xia) (Zihao Xia)
- Minrui Xu (@wsxmr1234) (Minrui Xu)
- Xinkai Tang (@Kai9613) (Xinkai Tang)
- Qicheng Chen (@Wayneecc) (Qicheng Chen)
