### ISSUE TITLE
Sprint 3 - Team 1 Enemy Design + Animation + AI

### ISSUE THREAD

**Issue by JZ1890** [UQdeco2800/2022-ext-studio-1#120]
# **Description**
Design enemies to enrich gameplay, enemies should have animations like NPCs, and different enemies will have different behavior preferences, For example, some are more aggressive, some others tend to run away

# **Dependencies**

- [x] #64 
- [x] Actual map

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Complete the enemy image design (Sep. 22)
- [x] Complete animation (Sep. 29)
- [x] Complete AI production (Oct. 3)
- [x] User testing (Oct. 4)

**Completion Deadline:** Oct. 4

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Junwen Zhu (@JZ1890)
- Hengyuan Lu (@Awe5omeTired)
- Jialin Yu (@tgswjty)
- Yan Jiang (@whateverchris)
