### ISSUE TITLE
Sprint 3 - Team 5 Scenario design + Scenario implementation

### ISSUE THREAD

**Issue by ShokuJO** [UQdeco2800/2022-ext-studio-1#121]
# **Description**
Design the Scenario for the village which is the core area of the game, player needs to finish the tasks to collect the scales in this area. Add missing components for the lab area. (At the end of the game, the player needs to restore Atlantics by opening the mechanism.)

# **Dependencies**

- [x] #64 
- [ ] #120 (movement of opening the mechanism)
- [ ] #117 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Complete the mechanism or key design (Sep. 22)
- [ ] Complete the Scenario design for opera (Sep. 24)
- [ ] Complete the design for components in the village (Sep.24)
- [ ] Complete the Scenario design for village (Sep. 25)
- [ ] Implent the Scenario (Sep. 29)

**Completion Deadline:** Oct. 4

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- JOJO (@ShokuJO) (Guanhao Qiao) 
- Qing Zhang (@Versprechen080) (Qing Zhang)
- Yuqiao Tong（@CodingDavid2）（yuqiaotong）
- Lulu Zhong (@lily441) (Lulu Zhong)

**Comment by JZ1890** [comment]
Hi, this is team 1, so far we have designed all the enemies (specifically in the enemy list), we want to ask about which maps each enemy should be deployed on, so that we can adjust it in the next sprint
