### ISSUE TITLE
Sprint 3 - Team 7 Feature ticket: Win/lose Condition for Selecting Traitors

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#122]
# **Description**
In the context of the game where Atlantis is about to sink, players need to find the information of the traitor who will cause the sinking of the continent through the quest, and after confirming the information, expel them from the continent to save Atlantis. So when the player uses the eviction menu (completed) to select an NPC they consider a traitor, the game will end. Based on this, we need to formulate a win-lose condition to display the current state of the game (whether it's over). This gives players instant feedback on how the game is progressing and how they need to win the game. In addition to this, it also makes the game structure more complete.

## SubFeature/component
- **Prompt box of winning** - Displays the winning information if the player selects the correct traitor. (e.g. Specific information and subsequent settings are formulated according to the storyline)
- **Prompt box of losing** - Displays the losing information if the player selects the wrong one. (e.g. this prompt will be displayed after the user has exhausted all selection opportunities)

## **Examples**
- **Win conditions (prompt box)** - If the player's choice is correct, the victory information will be displayed, and a organ or a key will be unlocked on the map at this time, and the player will trigger the organ or get the key to win the game.
- **Lose conditions (prompt box)** - If the player's choice is wrong, an error message will be displayed and the player will be told how many more chances to choose (3 chances in total, if they run out then Failure), wrong selection may result in debuffs such as reduced HP.

# **Dependencies**
- Display organ or key on the map  (Team5 ). And story line (#64 )
- Display the game status according to game end menu(Team 3).
- The Player Eviction Menu (#51  )

# **Milestones**
In order to implement the display part of the player eviction menu that can be used for interaction: 
- [ ] Goal 1: Determine the basic image of prompt box and confirm the win/lose logic, e.g. Is some logic required ? Like the number of errors and a way to save Atlantis (User survey + wiki) (Sep. 20)
- [ ] Goal 2: Design display effects of win/lose prompt box (hover, UI etc.), and design display styles (what to show).  (Sep. 23)
- [ ] Goal 3: User test and evaluation. (Sep. 23 - Oct. 3 ) (mainly before coding)
- [ ] Goal 4: Improve and Implement the prompt box (including content display) and integrate it into the game environment.(Sep. 25)
- [ ] Goal 5: Create and Implement the game logic of win/lose condition and match the prompt. (Sep. 28)

**Completion Deadline:** Sep. 30

# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)

# **Members**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Shaohui Wang (@Tonywangshaohui ) (shaohui wang)
- Kexin Du (@motaA0309 ) (Kexin Du)
- Qiansen Jin (@QiansenJhin )

**Comment by LIU-Evelyn** [comment]
The decision of basic win/lose condition and sub-feature: [Sprint3 - Win/lose Condition: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Eviction:-Win-lose-Condition-for-Selecting-Traitors-(Team-7))

**Comment by LIU-Evelyn** [comment]
The logic implementation can be found in Task ticket 3&4：[Task 3](https://github.com/UQdeco2800/2022-ext-studio-1/issues/134)
[Task 4](https://github.com/UQdeco2800/2022-ext-studio-1/issues/137)
