### ISSUE TITLE
Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#123]
# **Description**
In this feature, we are going to implement the collecting tasks inside each chapter that given by NPCs. We are going to collaborate with the NPC communication team, inventory team, and maybe some other teams that if needed. In this feature, we will design each collecting object and implement them with the collecting behavior of player.

## SubFeature/component (optional)

- object design
- connect to inventory
- connect with NPC interaction (when NPC gives player collecting task)

# **Dependencies**

- (#117  

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Finish image drawing of the Electricity Switch game in Chapter 1 (Sep. 17)
- [ ] Finish Coding Document for Electricity Switch game in Chapter 1 (Sep. 18)
- [ ] Implement the Electricity Switch game in Chapter 1
- [ ] Finish image drawing of other objects for collecting in the rest of the chapters (Sep. 21)
- [ ] Finish Coding Document for Collection Game in Chapter 3 (Sep. 19)
- [ ] Finish Coding Document for Collection Game in Chapter 2 
- [ ] Finish Coding Document for Collection Game in Chapter 5
- [ ] Finish Coding Document for Collection Game in Chapter 6
- [ ] Implement the Collecting Game in Chapter 3
- [ ] Implement the Collecting Game in Chapter 2
- [ ] Implement the Collecting Game in Chapter 5
- [ ] Implement the Collecting Game in Chapter 6
**Completion Deadline:** Oct. 05

# **Extras (optional)**
- [ ] If we have time we will try to do the music game in Chapter 4

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Jingyi Li (@AlynnLi) (Jingyi Li)
- Yifei Liu (@liu8868) (Yifei Liu)
- Yufan Chen (@snakefen) (Yufan)
- Junyu Zhu (@45190331) (Junyu_Zhue)
