### ISSUE TITLE
Sprint 3 - Team 9 Task Ticket 1: Object Image Drawing for Each Collecting Games

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#124]
# **Description**
**Feature:** [Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter](#123 )

This ticket is mainly for the object design documentation. Both the comment of this ticket and the wiki page will display the design and drawing of the objects that shows inside the collecting game of each chapter (Chapter 1, Chapter 2, Chapter 3, Chapter 5, Chapter 6).

# **Dependencies**
- [ ] [Grid Size and Resolution](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Pixel-Grid-Resolution) 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Finish all the object image drawings for the Electricity Switch Game in Chapter 1 (Sep. 17)
- [ ] Finish all the object image drawings for the Collecting Game in Chapter 2  (Sep. 19)
- [ ] Finish all the object image drawings for the Collecting Game in Chapter 3  (Sep. 20)
- [ ] Finish all the object image drawings for the Collecting Game in Chapter 4  (Sep. 21)
- [ ] Finish all the object image drawings for the Collecting Game in Chapter 2  (Sep. 22)
- [ ] Update wiki page of object image drawings (Sep. 24)
- [ ] Iterate any drawings if needed
- [ ] Upload all the drawings by Oct. 05
 
**Completion Deadline:** Sep. 22

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jingyi Li (@AlynnLi) (Jingyi Li)

**Comment by AlynnLi** [comment]
Broken Electricity Switch
![Electric Switch Broken](https://user-images.githubusercontent.com/110004991/190902922-570f1079-c35c-4218-ad30-cbfed0479855.png)

**Comment by AlynnLi** [comment]
Fixed Electricity  Switch
![Electric Switch](https://user-images.githubusercontent.com/110004991/190902948-5fbb90b8-1509-4067-bd87-3ad2f6c6eaa8.png)

**Comment by AlynnLi** [comment]
Tools for player to collect
![Tools](https://user-images.githubusercontent.com/110004991/190902972-40261f4c-e128-4a19-bc19-4119313553e8.png)

**Comment by AlynnLi** [comment]
Battery for player to collect
![Battery](https://user-images.githubusercontent.com/110004991/190902995-8b8ce712-996d-414e-b52f-032e07665d8b.png)

**Comment by AlynnLi** [comment]
coral
![coral](https://user-images.githubusercontent.com/110004991/193795130-03817862-be5f-4fc1-8635-4cc04c588a8d.png)

**Comment by AlynnLi** [comment]
Jellyfish
![jellyfish](https://user-images.githubusercontent.com/110004991/193795222-2daa888d-57b1-4e4c-bb4d-133ce65ed2dc.png)

**Comment by AlynnLi** [comment]
seaweed
![seaweed](https://user-images.githubusercontent.com/110004991/193795271-b9e38304-32e1-417a-bf27-cc8d4e2af6a8.png)
