### ISSUE TITLE
Sprint 3 - Team 9 Task Ticket 2: Collection Game in Chap 1

### ISSUE THREAD

**Issue by snakefen** [UQdeco2800/2022-ext-studio-1#126]
# **Description**
**Task:** [Collection Game in Chap 1]
**Feature:** [Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter](#123 )

To implement the collection game in chap1, players need to get hints to collect batteries when approaching the broken switch, and then return to repair the switch to get clues.

# **Dependencies**
- [x] storyline/general background  (#7 )
- [x] Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter(#123  )

# **Milestones**
- [ ] Finish code abstract (Sept. 20)
- [ ] Finish code (Sept. 21)
- [ ] Finish unit test (Sept. 22)
 
**Completion Deadline:** Sept.22
 
# **Documentation**
- [NPC Communication Play Script](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-Communication--Play-Script)]
 
# **Member**
- Yufan Chen(@snakefen ) (Yufan)
- Junyu Zhu(@45190331 )(DDD)
