### ISSUE TITLE
Sprint 3 - Team 7 task ticket 1: Determine the display of prompt box and win/lose logic

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#127]
# **Description**
**Task:** [Determine the basic image of prompt box and confirm the win/lose logic, e.g. Is some logic required ?](https://github.com/UQdeco2800/2022-ext-studio-1/issues/52)
**Feature:** [Win/lose Condition for Selecting Traitors: Goal 1](https://github.com/UQdeco2800/2022-ext-studio-1/issues/122)

Discuss with other teams, gather ideas and create questionnaires to determine the win/lose conditions. At the same time, think about the image and display of the prompt (win/lose prompt box), during which our team will determine how and what to show based on player (other students) preferences.
 
## **Example**
- **Survey**: Aggregate questionnaire and interview data to design the logic/image according to the wishes of the majority of respondents
- **What/how to show prompt**: According to the feature ticket, the prompt box will let the player know the state of the game and the choices they can make in next stage (after selecting the NPC). 

# **Dependencies**
- [ ] Information about basic win/lose condition relies on storyline (#64  ).
- [ ] Relevant display of prompt box relies on existing eviction menu (#51  ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Design the questionnaire and ready to use (Sep. 18)
- [ ] Step 2: Aggregate and analysis the data collected from questionnaire, then use wiki page to show the information/decision (Sep. 20)
 
**Completion Deadline:** Sep. 20 
 
# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
The questionnaire:
https://docs.google.com/forms/d/e/1FAIpQLScEUPMv0ylGGatJrF49Y2tYKf_JDraIwzqYUc41krZ84X5dAA/viewform?usp=sf_link

**Comment by motaA0309** [comment]
The summary of User Survey ：
https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu:-Win-lose-Condition-for-Selecting-Traitors-(Team-7)
