### ISSUE TITLE
Sprint 3 - Team 2 Task Ticket 1: Dialogs with NPC in Chapter 1-3

### ISSUE THREAD

**Issue by zihao-xia** [UQdeco2800/2022-ext-studio-1#128]
# **Description**
**Task:** [Dialogs with NPC in Chapter 1-3](#3).
**Feature:** [Sprint 3 - Team 2 Feature Ticket: Player interaction with Npc + aligning with storyline](#117 )

Dialogs with NPC in Chapter 1-3 will be implemented in the main game screen, and event handlers will be added to the dialog boxes so that the story can be pushed. Different Chapters will have different event handlers according to the storyline. Additionally, script files for each chapter will be added to be loaded as dialogs.
 
# **Dependencies**
- [ ] NPC Communication Stage 2 (#54 )
- [ ] Collection Game in Chap 1 (#126 )
 
# **Milestones**
- [ ] Complete Chapter 1 code (Sep. 19)
- [ ] Complete Chapter 2 code (Sep. 20)
- [ ] Complete Chapter 3 code (Sep. 21)
 
**Completion Deadline:** Sep. 21
 
# **Documentation**
- [NPC Communication Script](../wiki/NPC-Communication--Play-Script)
 
# **Member**
- Zihao Xia (@zihao-xia) (Zihao Xia)
- Xinkai Tang (@Kai9613) (Xinkai Tang)
