### ISSUE TITLE
Sprint 1 - Team 1 Character Design

### ISSUE THREAD

**Issue by JZ1890** [UQdeco2800/2022-ext-studio-1#13]
# **Description**
Team 1 will be working on character design. Based on the existing game design, the character design will affect the player's game flow, such as clue collection and character differentiation. In addition, a reasonable character design will ensure the consistency of the overall aesthetic style of the game to ensure the player's gaming experience.

## SubFeature/component (optional)

1. player character: player-controlled character
2. NPC: this will include neutral characters, enemies, etc. (based on game storyline and victory conditions)

# **Dependencies**

Game background style Team 5 #xx

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Complete the player character design (Aug. 20)
- [ ] Complete the NPC character design (Aug. 23)
- [ ] Optimized animation effects for characters (Aug. 26)
- [ ] User testing & evaluation (Aug. 28)

**Completion Deadline:** Aug. 30

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Junwen Zhu (@JZ1890)
- Hengyuan Lu (@Awe5omeTired)
- Jialin Yu (@tgswjty)
- Yan Jiang (@whateverchris)

**Comment by LIU-Evelyn** [comment]
Hi this is team 7, just want to ask about how do you want to show the NPC image on eviction menu card? If you want us to use your design directly，please commit it to the repo that we can find it. Or if it needs to be redesigned, please tell us, thank you.

**Comment by JZ1890** [comment]
> Hi this is team 7, just want to ask about how do you want to show the NPC image on eviction menu card? If you want us to use your design directly，please commit it to the repo that we can find it. Or if it needs to be redesigned, please tell us, thank you.
Hi, in our plan we intend to put animated characters into the relevant menu, however according to the current work progress we expect it will be difficult to deliver this in this sprint, we will do this in the next sprint to supplement this section.

**Comment by JZ1890** [comment]
> Hi this is team 7, just want to ask about how do you want to show the NPC image on eviction menu card? If you want us to use your design directly，please commit it to the repo that we can find it. Or if it needs to be redesigned, please tell us, thank you.

Hi, in our plan we intend to put animated characters into the relevant menu, however according to the current work progress we expect it will be difficult to deliver this in this sprint, we will do this in the next sprint to supplement this section.
