### ISSUE TITLE
Sprint 3 - Team 7 task ticket 2: Design display of win/lose prompt box

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#133]
# **Description**
**Task:** [ Design display effects of win/lose prompt box (hover, UI etc.), and design display styles ](https://github.com/UQdeco2800/2022-ext-studio-1/issues/53)
**Feature:** [Win/lose Condition for Selecting Traitors: Goal 2](https://github.com/UQdeco2800/2022-ext-studio-1/issues/51)

Based on feedback from completing goal 1, the display of detailed eviction cards has been determined through the studio. The interaction process will include two features: move mouse to cards (show the related basic information of NPC); click on cards (pop up a new window to show the related clues). Therefore, in this task, team will design the image and effect  of the menu according to this.
 
## **Example**
- **Detailed Eviction Cards**: Design the detailed interface for the eviction card, which mainly adds the Image, Name and Gender of NPCs.
- **Information/clues Windows**: Each NPC will have an eviction card (for the user to choose the traitor he considers). In order to help the player chooses the traitor more accurately, the information/clues window will popped up after he clicking the eviction card.

# **Dependencies**
- [x] Information about eviction character relies on storyline and character interactions (#7  and #9 ).
- [x] The basic image of NPC that shown on the cards depend on character design (#13 ).
- [x] The Player Eviction Menu (#4 ).
 
# **Milestones**
Steps that need to be completed for this task:
- [x] Step 1: Design draft of Detailed Eviction Card and Information/clues Window (Sep. 6)
- [x] Step 2: Improve the final image and effect of the feature, such as adding hovering, adjusting colors, etc. (Sep. 7)
 
**Completion Deadline:** Sep. 7

### Additional goals

# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [User survey for detailed eviction card](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu:-Detailed-Eviction-Cards-(Team-7))
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
| **Initial win prompt box** | **Initial lose prompt box**| 
| --------------- | --------------- | 
| ![WIN1](https://user-images.githubusercontent.com/88132643/191558924-50ef53e1-49ab-4b05-8d0f-199d53562661.png) | ![LOSE](https://user-images.githubusercontent.com/88132643/191558962-008bc867-f19d-4953-8c72-408cafefa269.png) |

**Comment by motaA0309** [comment]
My initial design idea was to make the win prompt box with the banner to be green to represent victory and success through the select traitor mission. In the part of the content box, the wooden boards and posters are used to create an atmosphere of celebration. On the outside of the content box, there are fireworks, confetti, and coloured streamers to represent the celebration. In the future, our team may optimize this part by adding animation or sound effects to the celebration elements to enhance the user experience.

The error box is banner red and also broken, then the content box below uses fault wind to indicate that the selection is incorrect and failed.

**Comment by LIU-Evelyn** [comment]
Added corresponding buttons:

| **Right button** | **Wrong button1** | **Wrong button2**| 
| --------------- | --------------- | --------------- | 
| ![rightBtn](https://user-images.githubusercontent.com/88132643/192743036-0468e4a8-bb34-40ca-969e-9708af811d23.png) | ![chanceBtn](https://user-images.githubusercontent.com/88132643/192743061-4e768c7c-c555-45d6-a908-65a8f90a8d4d.png) | ![chanceBtn2](https://user-images.githubusercontent.com/88132643/192743089-37e348b0-19e9-4113-b54a-f6fba5842445.png) |
