### ISSUE TITLE
Sprint 3 - Team 7 task ticket 3: Improve and Implement the prompt box

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#134]
# **Description**
**Task:** [Improve and Implement the prompt box (including content display) and integrate it into the game environment](https://github.com/UQdeco2800/2022-ext-studio-1/issues/134)
**Feature:** [ Win/lose Condition for Selecting Traitor: Goal 3](https://github.com/UQdeco2800/2022-ext-studio-1/issues/122)

The programmer will develop the UI based on the image of the improved win-lose prompt box and integrate it into the game. Before that, simple win-lose logic needs to be built to ensure that the prompt box interface corresponding to the user's selection is loaded in the appropriate situation.
 
## **Example**
- **Win prompt box**: After the user clicks to confirm to select a certain NPC, if he is a traitor, a win prompt box of "select correctly" will pop up, and the corresponding content will be displayed in it.
- **Lose prompt box**: After the user clicks to confirm to select a certain NPC, if he is not a traitor, a lose prompt box of "wrong selection" will pop up, and the corresponding content will be displayed in it. The lose prompt box will pop up twice, telling the player "two/one chance left" respectively.

### Additional Step
- After the user clicks the "confirm" button of the win prompt box, the image of the traitor telling how to save Atlantis will be loaded

# **Dependencies**
- Artistic design of prompt box (#133   ).
- Information about basic win/lose condition relies on storyline (#64  ).
- Display the game status according to game-end menu (#130  )
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Implement win prompt box and ready for use (Ignore logic and pop after selecting a certain npc to evict, e.g. Nereus or Zoe). (Sep. 23)
- [ ] Step 2: Implement lose prompt box and ready for use (Ignore logic and pop after selecting a certain npc to evict, e.g. Metis or Doris). (Sep. 24)
- [ ] Step 3: Create basic win/lose condition and ready for use (Better match the prompt box). (Sep. 25)
 
**Completion Deadline:** Sep. 25
 
# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [Sprint3 - Win/lose Condition: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Eviction:-Win-lose-Condition-for-Selecting-Traitor-(Team-7))
 
# **Member**
- Shaohui Wang (@Tonywangshaohui ) (shaohui wang)
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)

**Comment by LIU-Evelyn** [comment]
Integrated prompt box with basic logic and ready for use: https://github.com/UQdeco2800/2022-ext-studio-1/commit/6f90260f35398f1b5c4abc9821eb28e7144fcbc9

**Comment by LIU-Evelyn** [comment]
The detailed process can be found in: [Show corresponding game status after selecting traitor](https://github.com/UQdeco2800/2022-ext-studio-1/issues/135)
