### ISSUE TITLE
Implement the feature: Show corresponding game status after selecting traitor

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#135]
# **Description**
**Task:** [Create and Implement the game logic of win/lose condition and match the prompt](https://github.com/UQdeco2800/2022-ext-studio-1/issues/134)

**Purpose**: This ticket is for effective cooperation between two groups related to game status
**Function**: The win/lose prompt box will pop up after the player clicks the "confirm" button to select an NPC, and the window will display the content corresponding to win/lose status. After the game is over (such as choosing the right traitor and saving Atlantis or choosing the wrong one and running out of three chances), the game ending function created by Team3 will be called directly to display the complete game process and status.
 
## **Requirement**
After the player chooses the correct traitor, they will be given a way to save Atlantis, and the game will end when done.
After the player selects the wrong NPC, the end interface will not pop up until all three opportunities are used up.
- **Team 7**: Implement win/lose prompt box and create win/lose condition, call the ending function built by Team 3.
- **Team 3**: Create and implement the ending function according to the story line and possible endings and optimize it in time during the cooperation.

# **Dependencies**
- Team 7 task ticket 3&4: Win/lose prompt box (#134 ) and Game logic of win/lose condition
- Ending Menu (#130  ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Ending function (Sep. 26)
- [ ] Step 2: Match win-loss conditions to pop-up prompts box. (Sep. 27)
- [ ] Step 3: Adjust and optimize the game state when calling the ending function (Sep.29)
 
**Completion Deadline:** Sep. 29
 
# **Documentation**
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [Sprint3 - Win/lose Condition: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Eviction:-Win-lose-Condition-for-Selecting-Traitor-(Team-7))

 
# **Member**
- Shaohui Wang (@Tonywangshaohui ) (shaohui wang)
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Qiansen Jin (@QiansenJhin ) 
- Penda (@PendaZz) (Yaojun Tan)

**Comment by PendaZz** [comment]
Finish simple Ending Menu (Show win/lose status, restart game button, back to main menu button)

**Comment by LIU-Evelyn** [comment]
Win/lose logic for selecting traitor have been done: 
Select correct traitor and find key(use it)/3 chance to select traitor (run out then lose game)/Punishment mechanism
Can be found in https://github.com/UQdeco2800/2022-ext-studio-1/commit/a5e99935a9a262b3c9a24719d8de1446c6921d5d
https://github.com/UQdeco2800/2022-ext-studio-1/commit/57d6dbc46b669a00785d030ce9e900fd5ea404b2

**Comment by LIU-Evelyn** [comment]
Separated the game logic and optimized code structure：https://github.com/UQdeco2800/2022-ext-studio-1/commit/280e9148f2f7580e9209b2d057d4949b7fd77b63
