### ISSUE TITLE
Sprint 3 - Team 6: Clue Storage

### ISSUE THREAD

**Issue by YuOuyang99** [UQdeco2800/2022-ext-studio-1#136]
# **Description**
The clue storage plays a vital role because when the player interacts with the NPC, he can obtain the relevant clues and information about the current NPC by completing the NPC's tasks. Finally, by comparing with the traitor's information, it helps players to find out the traitor in the game.

# **Dependencies**
Existing clues #61 
Storyline #80 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1  Communicate with Group 9 for known clues(Sep. 20)
- [ ] Goal 2  Communicate with groups 2 and 9 about the need for clues storage. (Sep. 21)
- [ ] Goal 3 Write out the clue text.  (Sep. 25)
- [ ] Goal 4  Build clue storage. (Sep. 28)
- [ ] Goal 5 Testing the clue storage with other groups. (Oct.3)

**Completion Deadline:** Oct.5

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
-Shook Jern Chung (@ShookJern) (Shook Jern Chung)
-Yu Ouyang (@YuOuyang99) (Yu Ouyang)
-Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
-Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)
