### ISSUE TITLE
Scenario triggered after the player selects the correct traitor

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#139]
# **Description**
**Task:** [Create and Implement the game logic of win/lose condition and match the sub-feature](https://github.com/UQdeco2800/2022-ext-studio-1/issues/137)

**Purpose**: This ticket is for effective cooperation between two groups related to scenario triggered (relate to right selection)
**Function**: The window of information that traitor provided will pop up after the player clicks the "ok" button on win prompt box, and the window will display the content "Need to find key to save Atlantis". After the window is closed by the player, a key will appear on the map, and the player can win the game with the key.
 
## **Requirement**
After the player chooses the correct traitor, they will be given a way to save Atlantis - Find and collect the "Key"
- **Team 7**: Implement win/lose prompt box and create win/lose condition, call the corresponding function built by Team 5 after selecting the right traitor.
- **Team 5**: Create and implement the corresponding function to load the key on the map and ready for use.

# **Dependencies**
- Team 7 task ticket 4: Game logic of win/lose condition (#137 )
-  Scenario implementation (#121  ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Situational logic after selecting the right traitor (Sep. 29)
- [ ] Step 2: Load key function. (Sep. 30)
- [ ] Step 3: Adjust and optimize the state when calling the function (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [Sprint3 - Win/lose Condition: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Eviction:-Win-lose-Condition-for-Selecting-Traitor-(Team-7))

 
# **Member**
- Shaohui Wang (@Tonywangshaohui ) (shaohui wang)
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Qiansen Jin (@QiansenJhin ) 
- JOJO (@ShokuJO) (Guanhao Qiao)

**Comment by ShokuJO** [comment]
We have finished the key design, we will update the loading functions as soon as possible

**Comment by LIU-Evelyn** [comment]
traitor info window was ready for use: https://github.com/UQdeco2800/2022-ext-studio-1/commit/84417235c22c269a70d0f3f50a6ff66a727ecec2

**Comment by ShokuJO** [comment]
We have finished the key function:https://github.com/UQdeco2800/2022-ext-studio-1/actions/runs/3152325385

**Comment by ShokuJO** [comment]
You can see the detail in souce/core/src/main/com/deco2800/game/areas/ForestGameArea.java (spawnKey() function)

**Comment by LIU-Evelyn** [comment]
Now the logic: find and use the key to win the game has been done: https://github.com/UQdeco2800/2022-ext-studio-1/commit/a5e99935a9a262b3c9a24719d8de1446c6921d5d
