### ISSUE TITLE
Sprint 3 - Team 4: Cooperation with Team 7 to integrate clues and win/lose stats into player profile.

### ISSUE THREAD

**Issue by riotanabe** [UQdeco2800/2022-ext-studio-1#149]
# **Description**
**Task:** Cooperating with Team 7 to find out how to include stats about players' clues and win/lose into player profile.
**Feature:** Player Profile (#125)

Some of the stats/profiles that the player profile window displays is information about the number of clues the player has remaining, the number of times they have used up all their guesses and lost the game, and the number of times they won the game. In order to keep track of these values, we need to communicate with Team 7 to find out how we can use their variables (e.g. variable to keep track of how many incorrect guesses they made) in our component. The task is then to get these values and display it on the player profile page. 

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Game logic of win/lose condition (#137)
- [ ] Basic Layout of Player Profile (#148)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Basic Layout of Player Profile (Sep. 30)
- [ ] Communicate with team 7 about win/lose game logic (Oct. 2)
- [ ] Store player data (num of clues, num of losses, num of wins) (Oct. 3)
- [ ] Get and display data (Oct. 3)
 
**Completion Deadline:** Oct. 3
 
# **Member**
- Jeffrey (@jeffjeffUQ ) 
- Rio Tanabe (@riotanabe)

**Comment by riotanabe** [comment]
Discussion with Team 7

![Screen Shot 2022-10-03 at 1 59 25](https://user-images.githubusercontent.com/91102176/193463712-c017297d-eaea-4716-bd51-da9220525606.png)

![Screen Shot 2022-10-03 at 1 59 33](https://user-images.githubusercontent.com/91102176/193463717-4db63a6a-d84b-44da-97f9-51441b920009.png)
