### ISSUE TITLE
Sprint 1 - Team 3 Feature Ticket : Music

### ISSUE THREAD

**Issue by PendaZz** [UQdeco2800/2022-ext-studio-1#15]
# **Description**
This should be roughly a one paragraph description of the features / ideas on which your team plans to work. It should very briefly touch on why you think it should be in the game (e.g. "Adds an extra layer of depth to game play"). It should also describe how it will appear or be used in the final product (e.g. "On starting a level, the game will generate a random, procedurally-generated map").

# **Description**
BGM stands for background music. It refers to music that serves as a background in games, movies, TV dramas, etc., usually without a human voice. It is to render the atmosphere, enhance the overall performance of the picture.Every emotion, every change of tone in the design of the BGM must be the result of communication between the composer and the game designer, and this communication allows the composer and the game designer to integrate the creative and sound of the game. 
Background music in games can be broadly divided into these categories: BGM music, which is background music, and big map music;  Game Dynamic Sound: The musical effects that accompany the movement of a game character.

## SubFeature/component (optional)
Game background music: establishes the tone and mood of the game
Interactive sound effects: When the player operates, there is relevant sound effect feedback

## **Examples (optional)**
- **Win/lose Music**: Different music appears when the game is won or lost;
- **Start Game Music**: Background music when user opening the game;
- **Attack sound**: When there is an attack action, a sound effect will be played at the same time to highlight the action.

# **Dependencies**

- The background music atmosphere relies on the story tone and the game progress (#Team 5: Instructions & Storyline).
- The sound generated by interaction with the environment relies on the action design of the character(#Team 1: Character Design / Animation).

# **Milestones**
- [ ] Goal 1: Design the opening and background music base on the background story;
- [ ] Goal 2: Determine how long the music will be used for scenes
- [ ] Goal 3: Match sound effects to game scenes

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Dubbing according to the content of the dialogue.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. Richard (@AppleByter) (Richard Thomas)
Penda(@PendaZz) (Yaojun Tan)
Jason(@Jasonzcx)(Changxu Zhou)
4512678(@Jiayi Jiang)(Jiayi Jiang)
Shuhui Wang(@Aryawwww)(Shuhui Wang)
