### ISSUE TITLE
Sprint 1 - Team 3 Task Ticket 1: Background Music

### ISSUE THREAD

**Issue by PendaZz** [UQdeco2800/2022-ext-studio-1#16]
# **Description**
**Task:** [Background Music](#3).
**Feature:** [Sprint 1 - Team 3 Feature Ticket : Music](https://github.com/UQdeco2800/2022-ext-studio-1/issues/15#issue-1340332294)

Firstly, the tone of background music will be determined according to Team5's story background, and suitable music for the beginning and end of the game will be selected 
 
## **Example (optional)**
- **Title Music**: When the game starts, the background music gradually enters. If any other option happens the volume decreases accordingly。

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Confirm the back music style according to the game’s storyline and NPC reslationship.
- [ ] #Sprint_1_-_Team_5_Feature_ticket:_Instructions_&_Storyline
- [ ] #Sprint_1_-_Team_9_Task_Ticket_1:_NPC_Relationship_&_Clues
 
# **Milestones**
- [x] Step 1: Learn more about the background story given by Team5 and determine the tone of the story;
- [x] Step 2: Create background music corresponding to different scenes;
- [x] Step 3: Confirm the loop time and volume of the background music, etc. to achieve the best results.

**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jiayi Jiang(@45126768) (Jiayi Jiang)
- Penda(@PendaZz) (Yaojun Tan)
- Shuhui Wang(@Aryawwww)(Shuhui Wang)
- Jason(@Jasonzcx)(Changxu Zhou)
