### ISSUE TITLE
Reading data from JSON File

### ISSUE THREAD

**Issue by riotanabe** [UQdeco2800/2022-ext-studio-1#161]
# **Description**
**Task:** Read data from JSON File.
**Feature:** Player Profile(#125)

The task is to read data from a json file and display each property of data on the player profile window. The json file displays an array of objects which contains properties defining the player's performance in previous games. The average values from these data must be calculated and displayed on the player profile window, so that users can understand their overall performance in the game. 
 
## **Example (optional)**
- Average time taken to win the game
- Average number of guesses taken before winning the game 
- number of times they won
- number of times they lost.

# **Dependencies**
This task depends on the task of writing the results of the game to the player profile json file. 

- [ ] Writing player profile data to json file. (#162)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Read file (Oct. 3)
- [x] Process and display data on player profile window (Oct. 3)
 
**Completion Deadline:** Oct 3. 
 
# **Member**
- Rio Tanabe (@riotanabe)
