### ISSUE TITLE
Sprint 3 - Team 9 Task Ticket 2: Collection Game in Chap 2

### ISSUE THREAD

**Issue by snakefen** [UQdeco2800/2022-ext-studio-1#166]
# **Description**
**Task:** Collection Game in Chap 2
**Feature:** [Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter](#123 )

Implement the coral collection game in chap2. After the player has a dialogue with the NPC, he will choose different branch lines. When the player chooses to tell the truth in the option of concealing the truth/tell the truth, the npc will feel angry and will not have The collection game proceeds. When the player chooses to hide the truth, a collection game will be inserted for the player to collect five corals, and then the player will be given relevant clues.

# **Dependencies**
- [x] storyline/general background  (#7 )
- [x] Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter(#123  )

# **Milestones**
- [x] Finish code abstract (Oct. 4)
- [x] Finish code (Oct.4)
- [x] Finish unit test (Oct.4)
 
**Completion Deadline:** Oct.5

# **Documentation**
- [NPC Communication Play Script](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-Communication--Play-Script)
 
# **Member**
- Yufan Chen(@snakefen ) (Yufan)
- Junyu Zhu(@45190331 )(DDD)
