### ISSUE TITLE
Sprint 3 - Team 9 Task Ticket 2: Collection Game in Chap 3

### ISSUE THREAD

**Issue by snakefen** [UQdeco2800/2022-ext-studio-1#167]
# **Description**
**Task:** Collection Game in Chap 3
**Feature:** [Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter](#123 )

Implement the collecting game in chap3. The difference in this game is that what to collect depends mainly on the dialogue between the player and the NPC. In chap3, if the player chooses to tell the NPC the truth, he will be required to collect a coral, a jellyfish, and a seaweed. If the player tries to hide the truth, the amount of things collected is five times as high.
 

# **Dependencies**
- [x] storyline/general background  (#7 )
- [x] Sprint 3-Team 9 Feature Ticket: Collecting Game Inside Each Chapter(#123  )

# **Milestones**
- [x] Finish code abstract (Oct. 4)
- [x] Finish code (Oct.4)
- [x] Finish unit test (Oct.4)
 
**Completion Deadline:** Oct.5
 
# **Documentation**
- [NPC Communication Play Script](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-Communication--Play-Script)
 
# **Member**
- Yufan Chen(@snakefen ) (Yufan)
- Junyu Zhu(@45190331 )(DDD)
