### ISSUE TITLE
Sprint 1 - Team 6 Feature Ticket: Map Design

### ISSUE THREAD

**Issue by ShookJern** [UQdeco2800/2022-ext-studio-1#17]
# **Description**
In the context of the game that Atlantis is about to sink, players need to use the map function to find some information to lock the traitor and prevent Atlantis from sinking. It is not difficult to see that the function of the map plays a key role in the entire game. During the process of using the map, the player can be sent to different geographical locations and the interactive experience of the entire game can be increased by the player using the map.

## SubFeature/component 
- The map will express the spatial distribution of various things and places that exist throughout the game (according to existing storyline).
- There will always be a map icon on the main interface of the game to help players explore the game.

## **Examples**
- **Map Icon**: The overview of the map will be displayed/expanded after players clicked on the map icon on the main interface.

# **Dependencies**
- Information about what exists on the map relies on the storyline and character interactions (#Team 5: Instructions & Storyline and Team 9: Communication with NPCs).
- Information about the main interface map icon (#Team 7: Player Eviction Menu / GUI).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Understand the storyline of the entire game. (Aug. 20)
- [ ] Count the number of geographic locations on the map. (Aug. 23)
- [ ] Simple presentation of the content and style of the map. (Aug. 26)
- [ ] Complete the latest map content and styles for all current full versions. (Aug. 28)
- [ ] User tests and evaluation. (Aug. 28-29)

**Completion Deadline:** Aug. 30

# **Extras (Sprint 2)**
- [ ] The geographic locations that the player has explored and the geographic locations that the player has not yet explored are displayed in different colours on the map.
- [ ] There will be a hint on the map where there are NPCs.

## **Example (Extras)**
- **Differentiated locations**: Players can find out by using the map that the explored geographic locations will be coloured on the map. On the contrary, the unexplored places will be displayed in black.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Shook Jern Chung (@ShookJern) (Shook Jern Chung) 
- Yu Ouyang (@YuOuyang99) (Yu Ouyang)
- Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
- Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)

**Comment by YuOuyang99** [comment]
This is the latest map content and style for the current full version.
![Map](https://user-images.githubusercontent.com/110018552/187019742-9cb8e045-9948-4854-be72-0f24131a0d92.PNG)
