### ISSUE TITLE
Team 5 - Sprint3 - Task - Scenario design for village

### ISSUE THREAD

**Issue by ShokuJO** [UQdeco2800/2022-ext-studio-1#171]
# **Description**
**Task:** [Scenario design for village](#3)
**Feature:** [Scenario design and Scenario implementation](#121 )

The design is same as the lab design in sprint 2 which is the main scenario for the entire game. Players need to finish the tasks created in the scenario to collect the scales in order to finish the game, which means this scenario needs lots of area (like houses, castles) to clarify the npcs and tasks. So we aim to create an area contains lots of buildings.
 
## **Example**
- **Design style**: 
![image](https://user-images.githubusercontent.com/88018556/193858002-d3841450-c814-43ba-8598-c18f0518fecd.png)
We want to create a village based on the idea of 'Stardew Valley' , the npcs will be outside the buildings for players to interact.

# **Dependencies**
- [ ] Scenario design and scenario implementation (#121 )
- [ ] The scenario design must be fit for the character size (#107 )
- [ ] The design style must be same as the Lab Scenario (#79 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design the buildings and road  (Sep.24)
- [ ] Complete the whole design (Sep.25)
- [ ] User test for the scenario design (Sep.25)

 
**Completion Deadline:** Sep. 25
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Guanhao Qiao (@ShokuJO ) (Guanhao Qiao)
