### ISSUE TITLE
Team5-Implement Map

### ISSUE THREAD

**Issue by CodingDavid2** [UQdeco2800/2022-ext-studio-1#172]
# **Description**
**Task:** [Team5-Implement Map](#3).
**Feature:** [Scenario design and Scenario implementation](https://github.com/UQdeco2800/2022-ext-studio-1/issues/171#121)](#2)

This task is to add the village scene to the main game in sprint3. We created a lot of new elements (trees, houses) etc. This task is to convert the AI file we designed into in-game code.
 

# **Dependencies**

- [ ] Dependency 1 (The game must run smoothly and without bugs)
- [ ] Dependency 2 (The map must be beautiful and reasonable)

# **Milestones**
List of steps that need to be completed for this task.
- [ ]Assist in completing the design Step 1 (Sep.19)
- [ ]Replace Entity Step 2 (Sep 27)
- [ ]Final implement Step 3 (Oct. 5)

 
**Completion Deadline:** Oct.6

 
# **Member**
- YuqiaoTong (@CodingDavid2 ) (yuqiaotong)
