### ISSUE TITLE
Team5- Task Add key element into the game

### ISSUE THREAD

**Issue by CodingDavid2** [UQdeco2800/2022-ext-studio-1#173]
# **Description**
**Task:** [Add 'key' into the game](#3).
**Feature:** [Scenario design and Scenario implementation](https://github.com/UQdeco2800/2022-ext-studio-1/issues/171#121)](#2)

After the successful banishment of the murderer, the way to make Atlantis float again is to find the key, we this task is to design a key as a prop to add to the game.
 

# **Dependencies**

- [ ] Keys must meet aesthetic standards
- [ ] The key must match the overall painting style of the game 
- [ ]The key must be successfully added to the game as a prop and be free of bugs.

 
# **Milestones**
- [ ]Design for keys (Sep. 25th)
- [ ] Implement code (Sep. 28th)

 
**Completion Deadline:** Oct. 6

 
# **Member**
- YuqiaoTong (@CodingDavid2 ) (yuqiaotong)
