### ISSUE TITLE
Clues about showing NPCs

### ISSUE THREAD

**Issue by YuOuyang99** [UQdeco2800/2022-ext-studio-1#174]
# **Description**
task： Figure out which clues need to be shown to the player in the clue storage in the game.

Based on the known storylines and story chapters, you need to communicate with Team 2 and Team 7 to figure out which clues need to be shown to the player and which clues don't need to be shown to the player. The clues that the player sees from the expulsion menu are that what clues the player gets from the NPC will be displayed in the NPC related to the clue, otherwise, the clues that the player does not get will not be displayed in the expulsion menu.

## Requirement
- Requires Team 2 to complete the NPC dialogue from Chapter 4 to Chapter 6.
- The eviction menu of team 7 requires calling the clues that have unlocked the clue storage.

# **Dependencies**
-Team 9: NPC Communication Play Script (#9 )
-Team 5: Storyline (#80 )

# **Milestones**

- [ ] Goal 1: Carding clue (Sep. 25)
- [ ] Goal 2: Create documentation of required clues. (Sep.27 )
- [ ] Goal 3: The eviction menu provided to group 7 requires calling the clue bank with unlocked clues. (Oct. 3)

# **Documentation**
- [Clues filtered by storyline and all chapters](Link: https://docs.google.com/document/d/1_5xYX5oht9si-JBE0V-B1iwphNYMXsY5fAw5ll0i0Tw/edit?usp=sharing)

# **Members**
-Shook Jern Chung (@ShookJern) (Shook Jern Chung)
-Yu Ouyang (@YuOuyang99) (Yu Ouyang)
-Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
-Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)

**Comment by Kai9613** [comment]
The dialogue content in chapters 4 to 6 has been completed
[https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-communications-Chapter-456](url)

**Comment by LIU-Evelyn** [comment]
In order to show the clue that player collected from gameplay, the unlock clue should be displayed in informarion window ( in eviction menu)

**Comment by PhillipMike** [comment]
My bankcard is locked need help
