### ISSUE TITLE
Sprint 3 - Team 6 Task Ticket 2: Implementation and Testing for Clue Library

### ISSUE THREAD

**Issue by ShookJern** [UQdeco2800/2022-ext-studio-1#176]
# **Description**
**Task:** Implementation and Testing for Clue Library.
**Feature:** Clue Storage(#136 )

This task focuses on building the clue library that consists of all the clues in the game, and creating JUnit tests for it.
 
## **Example**
- **NPC clue**: Zoe - Zoe is one of the researches in the player's lab.
                         Metis - Metis can read the memory from the scale.
                         
# **Dependencies**
- Collated clues from the storyline and script (#174 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Collating clues documented by team members (Sept. 27)
- [x] Step 2: Coding the clue library according to the google docs consisting of collated clues (Oct. 1)
- [x] Step 3: Writing JUnit tests for NPC clues (Oct. 3)
- [x] Step 4: Documentation of JUnit tests updated on wiki (Oct. 4)
 
**Completion Deadline:** Oct. 4
 
# **Documentation**
- [Clue Storage](../wiki/Clue-storage-(-NPC-clues))
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
-Shook Jern Chung (@ShookJern) (Shook Jern Chung)
-Yu Ouyang (@YuOuyang99) (Yu Ouyang)
-Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
-Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)
