### ISSUE TITLE
Sprint 1 - Team 8 Feature Ticket: Inventory & Consumable Items

### ISSUE THREAD

**Issue by Tyza23** [UQdeco2800/2022-ext-studio-1#18]
# **Description**
This feature relates to how the user interacts with the game via the inventory menu, which will have functionality to both open on screen to display the players items, hold said items and maintain their characteristics for future use, and allow the player to use or discard items within their inventory. This feature will also be responsible for making items consumable (usable for a limited number of times by the player).

## SubFeature/component
Consumable items will be items that provide different attributes to the player or game that can only be activated a predetermined number of times before the item is lost. This feature will work to implement this functionality within the inventory system, tracking the uses of items and removing them from the player once they are used. 

## **Examples**
- **Hotkey**: The player can access the inventory by either pressing an onscreen button or a designated hotkey on their keyboard, e.g: 'i'
- **Time Extension Items**: The player may be able to use a consumable item that extends the play time before losing the game. This item may be only single use and would be a powerful item for the player if they are struggling with winning the game in the allotted time
# **Dependencies**

This feature will be dependent on Team 4 for the countdown clock as consumable items will need to directly affect the time given to players.

Both Team 1 and Team 7 will need to be liaised with to ensure a consistent menu and game aesthetic is presented by all features. 

# **Milestones**
- [x] Decide on style of inventory menu & available consumable items (Aug. 18)
- [x] Implement a working inventory system (Aug. 23)
- [x] Populate game with usable items(status effects not yet required) (Aug. 26)
- [x]  Attach  effects to each item, including making them consumable(Aug. 28)

**Completion Deadline:** End of Sprint 1

# **Extras**
- [ ] Have items that can be used together to form a stronger item (e.g 2 time buff items used together allows for the extension of time = 3 individual time buff items)
- [ ] Allow npc characters to drop items

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Ty Briggs(@Tyza23 )(Ty Briggs)
- Connor Ryan (@Connor-Ryan-1998)(Connor Ryan)
- Bohan Zhao (@Bohankkk)(Bohan Zhao)
- Shiyu Liu (@11shiyu)(shiyu Liu)
- Kwong Kit Tsang (@ivantsang9723)(Kwong Kit Tsang)

**Comment by Connor-Ryan-1998** [comment]
Completed
