### ISSUE TITLE
Sprint 4 - Team 8 Feature Ticket Improve Overall UI design(main menu), add lose condition(get attacked and lose game when hp was 0)

### ISSUE THREAD

**Issue by 11shiyu** [UQdeco2800/2022-ext-studio-1#180]
# **Description**
This sprint 4 will fix the bug that monsters won’t kill the player and will be stuck at the corner. We will implement the get attacked function to reduce HP,  and add another lose game condition when the player's HP gets to 0. In addition, we will keep improving the main menu UI, especially the background.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.
# **Dependencies**

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Improve main menu UI
- [ ] Get attacked and reduce HP function
- [ ] lose game function

**Completion Deadline:** End of Sprint 4

# **Extras (optional)**

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
Ty Briggs(@Tyza23)(Ty Briggs)
Connor Ryan (@Connor-Ryan-1998)(Connor Ryan)
Bohan Zhao (@Bohankkk)(Bohan Zhao)
Shiyu Liu (@11shiyu)(shiyu Liu)
Kwong Kit Tsang (@ivantsang9723)(Kwong Kit Tsang)
