### ISSUE TITLE
Sprint 4 - Team 7 Feature ticket: Improve features based on the win/lose logic and eviction menu ( Polishing tasks) 

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#183]
# **Description**
In the context of the game where Atlantis is about to sink, players need to find the information of the traitor who will cause the sinking of the continent through the quest, and after confirming the information, expel them from the continent to save Atlantis. At present, the game has a complete eviction menu function and win-lose logic related to expelling traitors. Based on this, In order to increase the attractiveness of the game, let players experience the game plot more immersively, We need to add some interesting improvements to make the game more "juicy", such as transition animations, special effects, sound effects, etc.

## SubFeature/component
- **Transition animations** - To visualize the Determine/Eviction process after selecting action.
- **Text display** - The content displayed in each window can be better adapted to different screen resolutions.
- **Special effects/ sound effects** - When part of the windows is popped up (prompt box.....)

## **Examples**
- **Transition animations - eviction process** -When the player triggers the **"select action"**, a transition animation will be displayed first, and the animation will show a process: judging whether the selected NPC is a traitor, and whether it is a traitor will correspond to different transition animations. When the transition animation disappears, a prompt box corresponding to the selection will pop up...
- **Special effects/ sound effects** - Different windows will correspond to different special effects and sound effects. For example, when the correct prompt box is popped up, there will be ribbons and cheers. When the error prompt box is popped up, there may be black fog and frustrated sounds, etc....
- **Text display** - At present, there is a large amount of text displayed in the expulsion menu. In order to ensure that players can have a better feeling, the display style of these texts needs to be perfectly adapted to different screen resolutions, such as size and position.

# **Dependencies**
- Story line (#64 )
- Win/lose condition(#122 ).
- The Player Eviction Menu (#51  )

# **Milestones**
In order to implement these polishing tasks that can be used for interaction: 
- [ ] Goal 1: Determine the basic image of transition animations and special effects , e.g. When and where need to add effects? What kind of animation effect the player wants to see? (User survey + wiki) (Oct. 11)
- [ ] Goal 2: Design display effects of transition animations (how many images, duration etc.), and design special effects (based on scenario). (Oct. 13)
- [ ] Goal 3: Design sound effects according to situations or actions (pop up the prompt box/clue window). (Oct. 14)
- [ ] Goal 4: User test and evaluation. (Oct. 11 - Oct. 16 ) (mainly before coding)
- [ ] Goal 5: Improve and Implement special effects and sound effects (the part really needed) and integrate it into the game environment.(Oct. 16)
- [ ] Goal 6: Implement the transition animation and match the select action, improve the text display. (Oct. 17)

**Completion Deadline:** Oct. 18

# **Documentation**
- [Main description of eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)

# **Members**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Shaohui Wang (@Tonywangshaohui ) (shaohui wang)
- Kexin Du (@motaA0309 ) (Kexin Du)
- Qiansen Jin (@QiansenJhin )

**Comment by LIU-Evelyn** [comment]
Goal1 can be checked from here: [Sprint 4 - Team 7 task ticket 1](https://github.com/UQdeco2800/2022-ext-studio-1/issues/191)

**Comment by LIU-Evelyn** [comment]
Goal 2 can be checked from here: [Sprint 4 - Team 7 task ticket 2](https://github.com/UQdeco2800/2022-ext-studio-1/issues/192)
After user testing, we went through multiple design iterations.

**Comment by LIU-Evelyn** [comment]
Goal 3 can be checked from here: [Sprint 4 - Team 7 task ticket 3](https://github.com/UQdeco2800/2022-ext-studio-1/issues/195)

**Comment by LIU-Evelyn** [comment]
Goal 4 can be checked from here: [Sprint 4 - Team 7 task ticket 2](https://github.com/UQdeco2800/2022-ext-studio-1/issues/196)
We spent 3 days user testing and redesigning our features.

**Comment by LIU-Evelyn** [comment]
Goal 5 can be checked from here: [Sprint 4 - Team 7 task ticket 5](https://github.com/UQdeco2800/2022-ext-studio-1/issues/198)
In the process of implementing particle effects, we tried various styles of effects, and the final image was fireworks and smoke.

**Comment by LIU-Evelyn** [comment]
Extra Goals:
In the process of implementing the transition animation, we found that there was still an unfinished display effect on the eviction card, so we added it as an additional task and communicated with Team 1 & 5 to advance it: [Cooperation ticket](https://github.com/UQdeco2800/2022-ext-studio-1/issues/204)

In addition to this, we also found that the action time of opening/closing the clue window was too short to match the duration of the sound effect well, so we made it another extra task and added animation on the clue window to make it match the sound effects. https://github.com/UQdeco2800/2022-ext-studio-1/commit/2dd904ce920c7f8ceeb78ece1d02582e328388cb
