### ISSUE TITLE
Sprint 4 - Team 9 Feature Ticket: Improvement of Collecting Games.

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#185]
# **Description**
In this sprint, our team will mainly focus on finish up the collecting games we did from last sprint. We are going to collaborate with other teams and trying to implement the collecting game as the logic is should be presented according to the storyline and scripts.

## SubFeature/component (optional)
1. Collaborating with the map team to implement the connection of the switch game and the main storyline (by showing the injured princess after the switch game) 
2. Collaborating with the NPC communication team to implement our collecting games (the tasks that NPCs give to the player) in-between the dialogues.

# **Dependencies**
1. Map implementation (Team 5) (#184)
2. NPC communication (Team 2) 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Communicate with Team 5
- [ ] Communicate with Team 2
- [ ] Finish up all the graphic design part for the rest of the games
- [ ] Implementation of the logic between the switch game and the map
- [ ] Implementation of the logic between the collecting games and the NPC dialogues

**Completion Deadline:** Oct. 27

# **Extras (optional)**
- [ ] The music game in Chapter 4 if we have time

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Jingyi Li (@AlynnLi) (Jingyi Li)
- Yifei Liu (@liu8868) (Yifei Liu)
- Yufan Chen (@snakefen) (Yufan)
- Junyu Zhu (@45190331) (Junyu_Zhue)
