### ISSUE TITLE
Sprint 4 - Team 2 Feature Ticket: Improvement of NPC interaction and integration with other teams’ features (mainly maps and clues)

### ISSUE THREAD

**Issue by zihao-xia** [UQdeco2800/2022-ext-studio-1#186]
# **Description**
In the Sprint 3, the dialogue is present from the beginning of the game until the end of the game, but this lacks the interactivity of the player with the NPC. So in Sprint 4, the dialogue will be opened after the player actively approaches the NPC, and can be called repeatedly in case the player misses some information.
In addition to the change and recall of the dialogue opening method, scene changes and clue exchanges when players interact with NPCs will also be integrated to enable the entire game to proceed smoothly.

## **Examples (optional)**
- **Dialogue with NPC**: When the player gets close to the NPC and presses a certain button, the dialogue will be opened. The player can click the dialogue box to move the plot forward until the dialogue ends, and this interaction can be conducted multiple times.
- **Clue exchange with NPC**: When the plot progresses to a specific node, the player will get corresponding clues after talking to the npc, thus promoting the development of the plot

# **Dependencies**
- Implementation of the rest game scenes (#184).
- Implementation of the clue library (Team 6).

# **Milestones**
- [ ] Modification of the clue description (Oct. 14)
- [ ] Dialogue recalling with corresponding NPC (Oct. 15)
- [ ] Method for dialogue opening when getting close to the NPC (Oct. 15)
- [ ] Integration with game scenes and the clue library (Oct. 17)

**Completion Deadline:** Oct. 19

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Zihao Xia (@zihao-xia)
- Minrui Xu (@wsxmr1234)
- Xinkai Tang (@Kai9613)
- Qicheng Chen (@Wayneecc)
