### ISSUE TITLE
Sprint 1 - Team 7 task ticket 2: Design the basic image of the eviction menu 

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#19]
# **Description**
**Task:** [Design the basic image of the eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/issues/8)
**Feature:** [Basic image and sub-feature of Player Eviction Menu: Goal 1](https://github.com/UQdeco2800/2022-ext-studio-1/issues/4)

Discuss with studio members and combine questionnaires to determine the basic art style, during which our team will determine how many sub-features will be included in the initial player eviction menu based on player (other students) preferences.
 
## **Example**
- **Survey**: Aggregate questionnaire and interview data to design the interface according to the wishes of the majority of respondents
- **Determine the eviction main menu**: This is the first interface the player will see after clicking on the expulsion menu, which may contain various information about the selected character.

# **Dependencies**
- [ ] Information about eviction character relies on storyline and character interactions (#Team 5: Instructions & Storyline and Team 9: Communication with NPC).
- [ ] Some image of character we will use may depends on character design (#Team 1: Character Design / Animation).
 
# **Milestones**
Steps that need to be completed for this task:
- [x] Step 1: Design the questionnaire and ready to use (Aug. 16)
- [x] Step 2: Aggregate questionnaire and interview data and create a document on wiki for other members of the studio to view (Aug. 17)
 
**Completion Deadline:** Aug. 17
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- ...
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
8.19 Meeting to discuss basic design draft:
![wireframe](https://user-images.githubusercontent.com/88132643/185782435-5a5a5af3-9037-4bbd-9dfd-81500420b16d.png)

**Comment by LIU-Evelyn** [comment]
Based on the sketch, we have designed the version 1, the original idea was that the art style of the puzzle game could be slightly irregular. But after designing it, we found that the completely irregular shape of the main menu looks a little weird after adding other elements (maybe the pictures are too cluttered):
<img width="670" alt="version1" src="https://user-images.githubusercontent.com/88132643/185783031-cb0599b4-8f0a-463e-b0fc-01594696e813.png">
Therefore, the group also tried the normal style, and finally found that the effect was not good:
<img width="670" alt="version2" src="https://user-images.githubusercontent.com/88132643/185783107-ce2d750f-5646-4001-8230-9f4399e81ab4.png">

**Comment by LIU-Evelyn** [comment]
（8.20）Disscussed with the studio and changed canvas aspect ratio to 16:9 when drawing. 
In the end we decided to design the main menu with just a few irregular graphics and add some elements to represent "Atlantis", but that's not the final version.
<img width="630" alt="version3" src="https://user-images.githubusercontent.com/88132643/185783755-6de105e9-03fa-4f48-8ef1-a9e1cf04b488.png">

**Comment by LIU-Evelyn** [comment]
Improved the title of the menu to align its art style with other elements:
<img width="670" alt="original_text" src="https://user-images.githubusercontent.com/88132643/185804933-e3325d36-bb49-40d8-b97e-a20cf04a6fb0.png">

Redesigned the text of title to make it more interesting and attractive：
<img width="670" alt="title_text" src="https://user-images.githubusercontent.com/88132643/185805081-dffd4e47-f580-47ee-ae2d-b6deca9d452b.png">

**Comment by LIU-Evelyn** [comment]
(8.21) Designed the signle eviction card (NPC card) and not as expected:
<img width="630" alt="Sketch" src="https://user-images.githubusercontent.com/88132643/185841492-65128682-ba00-4ff3-87b8-7821f9dc710d.png">

Redesigned and improved it：
<img width="630" alt="evictionCard_single" src="https://user-images.githubusercontent.com/88132643/185841663-ac3f6c34-50c3-4a80-80da-67e9b5a051fe.png">

**Comment by LIU-Evelyn** [comment]
(8.22) Step 2 is complete and the final menu image is shown below, with additional transparent backgrounds added to better blend in with other maps and game scenes:
<img width="630" alt="Menu_background" src="https://user-images.githubusercontent.com/88132643/185842361-fdf1cd71-cb78-43ef-be9a-f6a729c44d70.png">

**Comment by motaA0309** [comment]
(8.22) Step 3 completed the first draft for several ideas of menu button icons.
![49992d3f9750be96a3c8466a463b711](https://user-images.githubusercontent.com/109838814/185931634-81acf144-b437-4294-83bc-d728e37c702e.jpg)

**Comment by motaA0309** [comment]
(8.22) Step 3: the first draft of several ideas for the menu button icon.
![49992d3f9750be96a3c8466a463b711](https://user-images.githubusercontent.com/109838814/185932136-9721c071-a589-4643-88b6-6fbce9c5f905.jpg)

**Comment by LIU-Evelyn** [comment]
After a meeting on August 20, the team decided to add a menu icon, a button to select the card, and a query box to confirm the selection. These can increase the interactivity of the game.

**Comment by LIU-Evelyn** [comment]
(8.25) Step 4: Design the confirmation box (is used to confirm selection) [completed]
The win conditions may be added by other teams in the future.
<img width="630" alt="confirmation_box" src="https://user-images.githubusercontent.com/88132643/187022724-15e3c0f9-3b19-42c2-9d5e-dd42c9315984.png">

**Comment by LIU-Evelyn** [comment]
(8.27) Step 5: Button designed to select eviction card. [completed]
We may add animations for selection effects in the future....
<img width="370" alt="selectButton_single" src="https://user-images.githubusercontent.com/88132643/187022850-a1f6cb73-d31b-4d17-b56a-a6096652f996.png>

**Comment by motaA0309** [comment]
(8.22) Step 3: the final version of the menu button icon. The black text version will fit on a light background color, while the white text will suit a darker colored background.
> <img width="400px" alt="menuIcon_white" src="https://user-images.githubusercontent.com/109838814/187056542-23bb2dfb-0837-469d-8534-96a5f66c540d.png"> 
><img width="400px" alt="menuIcon_black" src="https://user-images.githubusercontent.com/109838814/187056547-26f2352e-d610-4104-b6b1-1f1fa0f371ab.png">
