### ISSUE TITLE
Sprint 4 - Team 7 task ticket 1: Determine the basic image of transition animations and special effects

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#191]
# **Description**
**Task:** [Determine the basic image of transition animations and special effects , e.g. When and where need to add effects? What kind of animation effect the player wants to see? ](https://github.com/UQdeco2800/2022-ext-studio-1/issues/127)
**Feature:** [Improve features based on the win/lose logic and eviction menu: Goal 1](https://github.com/UQdeco2800/2022-ext-studio-1/issues/183)

Discuss with other teams or potential users, gather ideas and create questionnaires to determine how and where to add the polishing elements (tranistion animation/special effects etc...). At the same time, think about the image and display of these during which our team will determine it based on player (other students) preferences.
 
## **Example**
- **Survey**: Aggregate questionnaire data to design the image and the way it appears according to the wishes of the majority of respondents
- **Where/how to show these elements**: According to the feature ticket, for example, the purpose of adding a tranistion animation is to visualize the eviction process and enhance the user's experience (more interesting interactions). 

# **Dependencies**
- [ ]Win/lose condition for selecting the traitor (#122   ).
- [ ] Relevant display of animation/effect relies on existing eviction menu (#51  ).
- [ ] The image of npc for evicting relies on storyline (#64 ).
 
# **Milestones**
Steps that need to be completed for this task:
- [x] Step 1: Design the questionnaire and ready to use (Oct. 7)
- [x] Step 2: Aggregate and analysis the data collected from questionnaire, then use wiki page to show the information/decision (Oct. 11)
 
**Completion Deadline:** Oct. 11
 
# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [NPC information](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-info)
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
[Link of Google questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSdaECD-WIMH_Me0a61UL973wpr-fQAzq0_0OguKkgXZHys_QA/viewform?usp=sf_link)

**Comment by LIU-Evelyn** [comment]
Data gathering and analysis were shown on wiki: https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Team7:User-Survery-Improve-features-based-on-the-win-lose-logic-and-eviction-menu-(-Polishing-tasks)
