### ISSUE TITLE
Sprint 4 - Team 7 task ticket 2: Design display effects of transition animations and special effects

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#192]
# **Description**
**Task:** [ Design display effects of transition animations (how many images, duration etc.), and design special effects (based on scenario)](https://github.com/UQdeco2800/2022-ext-studio-1/issues/133)
**Feature:** [Improve features based on the win/lose logic and eviction menu: Goal 2](https://github.com/UQdeco2800/2022-ext-studio-1/issues/183)

After analysing the feedback gathered from user survey, the basic display logic and style of tranistion animation/special effects have been determined through the studio. In terms of design, we will design two or three types to present the tranistion animation as well as special effects and prepare for the A/B testing that we will do in user testing. The interaction process may include: visualize the eviction process and Display the corresponding effects around the prompt box according to the selection result.
 
## **Example**
- **Tranistion animation**: After the user selects an NPC: A: shows the eviction animation with a specific (corresponding) NPC image throughout the whole process ; B: when the eviction animation starts, the image of the NPC is uncertain, and the corresponding NPC will not be displayed until the result is judged;.
- **Special effects**: When the correct prompt box is popped up, there will be ribbons. When the error prompt box is popped up, there may be black fog etc....

# **Dependencies**
- [x] Win/lose condition for selecting the traitor (#122   ).
- [x] Npc infomation and storyline (#64 ).
- [x] Display styles relies on feedback gathered form the studio (#191   ).
 
# **Milestones**
Steps that need to be completed for this task:
- [x] Step 1: Design draft of tranisation animation and special effects and prepare for user testing (Oct. 13)
- [ ] Step 2: Improve the final image and effect of the feature after user testing (collect data). (Oct. 15)
 
**Completion Deadline:** Oct. 15

# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [Sprint4 - Polishing-tasks: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Team7:User-Survery-Improve-features-based-on-the-win-lose-logic-and-eviction-menu-(-Polishing-tasks))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [NPC information](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-info)
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
**The idea and draft of animation process:**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| <img width="874" alt="draft1" src="https://user-images.githubusercontent.com/88132643/195505802-98bb4c2b-b5bc-4d93-96c3-4f6c0826343f.png"> | <img width="576" alt="draft2" src="https://user-images.githubusercontent.com/88132643/195505858-ba94d633-0da2-4258-bf3a-547ad8d2d001.png"> | <img width="736" alt="draft3" src="https://user-images.githubusercontent.com/88132643/195505888-f19b4410-de8e-4654-8359-4f811d4d1dcb.png"> |
If it is the correct or wrong selection:
| **Wrong selection** | **Correct selection**|
| --------------- | --------------- |
| <img width="674" alt="draft4" src="https://user-images.githubusercontent.com/88132643/195506055-d1d5d5dc-b8c5-46dc-8e0e-276f5bafd9c3.png"> | <img width="698" alt="draft5" src="https://user-images.githubusercontent.com/88132643/195506114-47a822b8-e3b6-4217-a296-2fbea90db02a.png"> |

**Comment by LIU-Evelyn** [comment]
**Based on the idea and draft, we designed the initial image and it will be improved in next stage:**

**Plan A-1**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![transition1](https://user-images.githubusercontent.com/88132643/195506846-cc288a1e-3000-4680-b02b-de2e41f7f73c.png) | ![transition2](https://user-images.githubusercontent.com/88132643/195506888-0d4a20ec-27fc-4767-b2a1-adf3fe8bb4da.png) | ![transition3](https://user-images.githubusercontent.com/88132643/195506929-c00c97da-4012-4fe7-96e0-5089e0af409d.png) |

**If it is the correct or wrong selection:**
| **Wrong selection** | **Correct selection**|
| --------------- | --------------- |
| ![transition5](https://user-images.githubusercontent.com/88132643/195506976-6b2a6091-a618-456c-8d49-8322cc264479.png) | ![transition4](https://user-images.githubusercontent.com/88132643/195507014-527652f1-e8f1-47d6-ba6d-e7a45fd86c6b.png) | 

**Plan B-1**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Metis1](https://user-images.githubusercontent.com/88132643/195507299-361fcf48-207e-4adc-b6cd-471d144340bb.png) | ![Metis2](https://user-images.githubusercontent.com/88132643/195507342-6a0501fd-ea55-4d70-b11f-ae83ffafa794.png) | ![Metis3](https://user-images.githubusercontent.com/88132643/195507415-12c88bdf-7463-47ff-b912-226b07f50b94.png) |

**If it is the correct or wrong selection:**
| **Wrong selection** | **Correct selection**|
| --------------- | --------------- |
| ![transition5](https://user-images.githubusercontent.com/88132643/195506976-6b2a6091-a618-456c-8d49-8322cc264479.png) | ![prince4](https://user-images.githubusercontent.com/88132643/195507488-36d51f3c-f14a-46f5-9996-c87e80ba9391.png) |

**Comment by motaA0309** [comment]
**Based on the idea and draft, I further designed the transition animation based on 8 different NPC characters**

**Doris**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Doris1](https://user-images.githubusercontent.com/109838814/196065229-482d3a50-4edb-45dd-8bc3-05ed4d98d168.png) | ![Doris2](https://user-images.githubusercontent.com/109838814/196065241-a6901cce-32e3-488c-b4e1-a92d682a7bd7.png) | ![Doris3](https://user-images.githubusercontent.com/109838814/196065244-637f5584-4177-4232-b9ba-84721c878083.png) |


**Heph**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Heph1](https://user-images.githubusercontent.com/109838814/196065289-5b25496c-6391-44d2-9cc8-f2a1fe3aaf5a.png) | ![Heph2](https://user-images.githubusercontent.com/109838814/196065292-665d2ef4-07b3-489d-a017-e1701f46cc7d.png) | ![Heph3](https://user-images.githubusercontent.com/109838814/196065299-1441c4f5-9cb7-42df-b0b3-bcd00b941ed5.png) |

**Metis**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Metis1](https://user-images.githubusercontent.com/109838814/196065345-39ee7b59-df6b-4398-9459-2cf59ed9db5e.png) | ![Metis2](https://user-images.githubusercontent.com/109838814/196065349-dd26ba75-f876-4a0b-8d65-2e25044f4dd0.png) | ![Metis3](https://user-images.githubusercontent.com/109838814/196065353-efabf8af-0896-44dc-9459-8b3b2959f3fd.png) |


**Nereus**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Nereus1](https://user-images.githubusercontent.com/109838814/196065400-b7a4ac48-24c5-42e4-9275-90f3617a1cc9.png) | ![Nereus2](https://user-images.githubusercontent.com/109838814/196065406-2e4ee7cc-c334-490b-99a3-0c3485910a02.png) | ![Nereus3](https://user-images.githubusercontent.com/109838814/196065414-0b132c0f-f10b-441f-bf27-efa1cf0fc898.png) |


**Orpheus**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Orpheus1](https://user-images.githubusercontent.com/109838814/196065467-c6192a4a-8cc0-454c-9899-e79349ac299b.png) | ![Orpheus2](https://user-images.githubusercontent.com/109838814/196065469-8e4891f4-b4fc-43d1-aaf0-4f144ff111a6.png) | ![Orpheus3](https://user-images.githubusercontent.com/109838814/196065475-1076bb66-d8f7-4cba-a485-839cea0eaa41.png) |

**Prince**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![prince1](https://user-images.githubusercontent.com/109838814/196065508-83fb89a5-dbc3-48db-bc7f-53004765d798.png) | ![prince2](https://user-images.githubusercontent.com/109838814/196065519-09ccac7a-15a1-4164-bcff-b0d2c5b62b32.png) | ![prince3](https://user-images.githubusercontent.com/109838814/196065521-7e4cfe4f-fdb4-461e-9c42-676bf13fe681.png) |


**Zeus**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Zeus1](https://user-images.githubusercontent.com/109838814/196065600-36d509a1-16fe-4632-a706-7c08244e5a75.png) | ![Zeus2](https://user-images.githubusercontent.com/109838814/196065607-c6ac9ca6-9280-4352-b800-66a7100e4ab6.png) | ![Zeus3](https://user-images.githubusercontent.com/109838814/196065612-fb031ffd-490f-4616-a4b2-252fe0d9e91e.png) |

**Zoe**
| **Process 1** | **Process 2**| **Process 3**|
| --------------- | --------------- | --------------- |
| ![Zoe1](https://user-images.githubusercontent.com/109838814/196065655-62011984-85f7-4c3f-a11c-fc2e1d47038d.png) | ![Zoe2](https://user-images.githubusercontent.com/109838814/196065660-594e4ed4-5c09-4b9e-b0c0-159ed857e386.png) | ![Zoe3](https://user-images.githubusercontent.com/109838814/196065665-a4370851-676d-4b46-89d6-4ccec6ca2025.png) |

**If it is the correct or wrong selection:**
| **Wrong selection** | **Correct selection**|
| --------------- | --------------- |
| ![playerFail](https://user-images.githubusercontent.com/109838814/196065746-75c835fa-f6a0-4bb4-a437-82815512d613.png) | ![prince4](https://user-images.githubusercontent.com/109838814/196065753-02314f7f-46d7-42fc-b8cb-0bd9fe59129f.png) |
