### ISSUE TITLE
Sprint 4 - Team 2 Task Ticket 1: Dialogue reacalling with corresponding NPC

### ISSUE THREAD

**Issue by zihao-xia** [UQdeco2800/2022-ext-studio-1#194]
# **Description**
**Task:** [Dialogue reacalling with corresponding NPC](#193).
**Feature:** [Improvement of NPC interaction and integration with other teams’ features (mainly maps and clues)](#186)

To restructure the dialogue system, the same dialogue texts need to be able to recalled for multiple times by the player, thus the dialogue box trigger method needs to be changed from directly showing up on the screen to pressing a certain button when the player gets close to the NPC. To achieve this, dialogue texts need to be attached to NPCs, but not all the NPCs are placed in the game now, so the NPCs need to be placed first.
 
## **Example (optional)**
- **Dialogue with NPC**: When the player gets close to the NPC and presses a certain button, the dialogue will be opened. The player can click the dialogue box to move the plot forward until the dialogue ends, and this interaction can be conducted multiple times.

# **Dependencies**
- [ ] Implementation of the rest game scenes in order to place NPCs (#184)
- [ ] Dialogues with NPC in Chapter 1-6 (#128)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Place all NPCs into the game (Oct. 13)
- [ ] Attach dialogue scripts to NPCs (Oct. 13)
- [ ] Develop the trigger method of the dialogue (Oct. 14)
- [ ] Integration (Oct. 15)
 
**Completion Deadline:** Oct. 15
 
# **Documentation**
- [NPC Communication Script](../wiki/NPC-Communication--Play-Script)
- [NPC info](../wiki/NPC-info)
 
# **Member**
- Zihao Xia (@zihao-xia)
