### ISSUE TITLE
Sprint 4 - Team 7 task ticket 3: Design sound effects according to situations or actions

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#195]
# **Description**
**Task:** [Design sound effects according to situations or actions (pop up the prompt box/clue window)](https://github.com/UQdeco2800/2022-ext-studio-1/issues/192)
**Feature:** [Improve features based on the win/lose logic and eviction menu: Goal 3](https://github.com/UQdeco2800/2022-ext-studio-1/issues/183)

After analysing the feedback gathered from user survey, our team determinded where we should add a sound effect to make the game more "juicy" by collecting the ideas of studio. In terms of design, since there are many elements containing "action" in the eviction menu, such as "select button"; "eviction card"; "mouseover", etc., adding sound effects to too many elements may negatively optimize the user's experience. Therefore, we will only add sound effects to some "actions", such as when the clue window and prompt window pop up.
 
## **Example**
- **Sound effect of clue window**: When the user clicks the npc card to view the clue, the sound of "fliping the page" will be triggered along with the clue window popping up.
- **Sound effect of prompt boxes**: After judging whether the result selected by the user is correct or incorrect, the corresponding prompt box will pop up and trigger cheering or frustrated sounds.

# **Dependencies**
- [x] Win/lose condition for selecting the traitor (#122   ).
- [x] Npc infomation and storyline (#64 ).
- [x] Display styles relies on feedback gathered form the studio (#191   ).
 
# **Milestones**
Steps that need to be completed for this task:
- [x] Step 1: Find inspiration in life to design foundational sounds (Oct. 12)
- [ ] Step 2: Further optimize the sound to match the game scene. (Oct. 14)
 
**Completion Deadline:** Oct. 14

# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [Sprint4 - Polishing-tasks: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Team7:User-Survery-Improve-features-based-on-the-win-lose-logic-and-eviction-menu-(-Polishing-tasks))

 
# **Member**
- Qiansen Jin (@QiansenJhin )

**Comment by QiansenJhin** [comment]
Find inspiration from life to capture sources for audio production.

**Comment by QiansenJhin** [comment]
Modify the audio format to fit libgdx, and add new sound effects for cluewindow and promptBox.

**Comment by LIU-Evelyn** [comment]
Implementation that relate to sound effects have been finished:
Related task ticket:
Related commit: https://github.com/UQdeco2800/2022-ext-studio-1/commit/786fd01fde45e3495c109d716874e7a38286c807 https://github.com/UQdeco2800/2022-ext-studio-1/commit/5326765583e781afcbe7c5b36130c2138f2b1628 https://github.com/UQdeco2800/2022-ext-studio-1/commit/704fb16908896c0a8113030b8ffc5e9c3888066b
