### ISSUE TITLE
Sprint 4 - Team 7 task ticket 4: User testing and evaluation

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#196]
# **Description**
**Task:** [User testing and evaluation: display and interaction of transition animation/special effects/sound effect](https://github.com/UQdeco2800/2022-ext-studio-1/issues/192)
**Feature:** [Improve features based on the win/lose logic and eviction menu: Goal 4](https://github.com/UQdeco2800/2022-ext-studio-1/issues/183)

To save development time and cost, after delivering the initial interaction design, we need to conduct user testing to assess whether the design meets player expectations. And find out the most suitable interactive process/images to deliver to developers for further development.
 
## **Example**
- **A/B testing**: Show participants different displays on transition animations and gather their aesthetic/interaction opinions.
- **Questionnaire**: Quantitative and qualitative data were collected from participants through short questions after completing the task plan.
- **Interview**: Supplement for further points.

# **Dependencies**
- [x] Win/lose condition for selecting the traitor (#122   ).
- [x] Design display effects of transition animations and special effects (#192  ).
- [x] Design sound effects according to situations or actions (#195    ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Design the questionnaire and ready to use, set the test plan(Oct. 14)
- [ ] Step 2: Aggregate and analysis the data collected from user testing, then use wiki page to show the result and deliver to developers. (Oct. 15)
 
**Completion Deadline:** Oct. 15

# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [NPC information](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-info)
- [Sprint4 - Polishing-tasks: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Team7:User-Survery-Improve-features-based-on-the-win-lose-logic-and-eviction-menu-(-Polishing-tasks))

 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
Step: The wiki page to show the result and deliver to developers - [Sprint 4 - User testing](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/User-Testing-for-Polish-Tasks-(-special-effects,-transition-animation,-and-sound-effects))
