### ISSUE TITLE
Sprint 4 - Team 1 Feature Ticket: Improvement of Enemy and Attack Function

### ISSUE THREAD

**Issue by JZ1890** [UQdeco2800/2022-ext-studio-1#197]
# **Description**
In sprint 3, the team has basically completed the enemy's design, animation and AI development, and additionally made a simple attack function. In this sprint, the team will further improve the enemy's performance in the game, such as adding hit animation, which will make the game content more juicy. As for the attack function, further enriching the player's attack methods will promote the gameplay.

# **Dependencies**

- [x] #157
- [ ] #120

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Improved enemy animations (Oct. 12)
- [ ] Add hit animation to enemy (Oct. 14)
- [ ] Increase the player's attack method (Oct. 16)
- [ ] Attack balance(Oct. 19)

**Completion Deadline:** Oct. 19

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Junwen Zhu (@JZ1890)
- Hengyuan Lu (@Awe5omeTired)
- Jialin Yu (@tgswjty)
- Yan Jiang (@whateverchris)
