### ISSUE TITLE
Sprint 4 - Team 7 task ticket 5: Improve and Implement special effects and sound effects

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#198]
# **Description**
**Task:** [Improve and Implement special effects and sound effects (the part really needed) and integrate it into the game environment](https://github.com/UQdeco2800/2022-ext-studio-1/issues/137)
**Feature:** [Improve features based on the win/lose logic and eviction menu: Goal 5](https://github.com/UQdeco2800/2022-ext-studio-1/issues/183)

In the current game, players can already experience the complete process of expelling traitors through the eviction menu, and smoothly trigger the win/lose logic associated with it. Whenever a player uses an element in the eviction menu, such as viewing a clue or selecting an NPC, the corresponding "clue window"/"prompt box" will pop up. Since "The Atlantis Sinking" is a puzzle game, in order to make the game more "juicy", adding appropriate animations and special effects between these action interactions can make the player's experience in the game more immersive.
 
## **Example**
- **Sound effects**: In order to increase the player's experience, when using the eviction menu, some interesting sound effects will be triggered: for example, when opening the menu, viewing npc clues, and popping up correct/wrong prompt boxes.
- **Special effects**: Although we have used distinctive elements in the design of the prompt box to distinguish different selection results, but to further reflect the state of the game - the special effect indicating the celebration will be triggered when the correct prompt box pops up; the special effect indicating "bad situation" will be triggered when the wrong prompt box pops up. Such as fireworks, black fog, etc.

# **Dependencies**
- [x] Win/lose condition for selecting the traitor (#122   ).
- [x] Design sound effects according to situations or actions (#195    ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Integrate sound effects corresponding to interactive actions into the game. (Oct. 14)
- [ ] Step 2: Create appropriate particle effects and integrate them into the game: when the correct/wrong prompt box pops up. (Oct. 15)
- [ ] Step 3: Improve the display effect, so that different effects are closer to the corresponding game state. (Oct. 16)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [NPC information](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-info)
- [Sprint4 - Polishing-tasks: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Team7:User-Survery-Improve-features-based-on-the-win-lose-logic-and-eviction-menu-(-Polishing-tasks))
 
# **Member**
- Shaohui Wang (@Tonywangshaohui ) (shaohui wang)

**Comment by LIU-Evelyn** [comment]
Already integrated all corresponding sound into the eviction menu: 
https://github.com/UQdeco2800/2022-ext-studio-1/commit/786fd01fde45e3495c109d716874e7a38286c807 https://github.com/UQdeco2800/2022-ext-studio-1/commit/5326765583e781afcbe7c5b36130c2138f2b1628 https://github.com/UQdeco2800/2022-ext-studio-1/commit/704fb16908896c0a8113030b8ffc5e9c3888066b

**Comment by Tonywangshaohui** [comment]
Step2:Already integrated all corresponding special effect when the correct/wrong prompt box pops up.[https://github.com/UQdeco2800/2022-ext-studio-1/commit/657ad9286df1b5bc58a790c1ea63a70c743fbaff](url)

**Comment by LIU-Evelyn** [comment]
Step 3:  Improve the display effect and changed the effects colour https://github.com/UQdeco2800/2022-ext-studio-1/commit/8b4257eff84612e5025e33907282fbdaacfed5c9
