### ISSUE TITLE
Sprint 1 - Team 6 task ticket 1: map implementation

### ISSUE THREAD

**Issue by zlz8848** [UQdeco2800/2022-ext-studio-1#20]
# **Description**
**Task:** [Determine the basic style and elements of the map].
**Feature:** [Map design](#17 )

Discuss with members to determine the basic art style, during which time our team will meet to determine the size of the map and what content elements will be present.

## **Example (optional)**
- Part1 : Brian storm fills the frame detail elements of the map
- Part2 : Determine the main map colors and placement of geographic locations

# **Dependencies**
Information about the map relies on the storyline and character interactions
- [ ] Team 5: Instructions & Storyline  (#7 ) 
- [ ] Team 9: Communication with NPCs(#9 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1 Hold a group meeting and determine the content and elements of the map;(August 20)
- [ ] Step 2 Record members' brainstorms and ideas on miro;(August 20)
- [ ] Step 3 Sketch the basic structure of the map;
 
**Completion Deadline:** Aug. 23

example：
https://miro.com/app/board/uXjVPdxfDX8=/
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Shook Jern Chung (@ShookJern) (Shook Jern Chung)
- Yu Ouyang (@YuOuyang99) (Yu Ouyang)
- Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
- Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)

**Comment by YuOuyang99** [comment]
A meeting was held on August 19 and a basic draft of the map was discussed：
<img width="1133" alt="miro ：brainstorm" src="https://user-images.githubusercontent.com/110018552/186448614-12ad3dc5-31db-4457-9795-f0f56b016ee8.png">

**Comment by YuOuyang99** [comment]
After group discussions, a sketch of the map has taken shape.
![map sketch](https://user-images.githubusercontent.com/110018552/186449473-9f25e7ff-59c3-4e5f-9144-9b6d9b49c500.png)
