### ISSUE TITLE
Sprint 4 - Team 6 Feature ticket 1: Cheerful sound effects when players complete npc tasks

### ISSUE THREAD

**Issue by zlz8848** [UQdeco2800/2022-ext-studio-1#200]
# **Description**
When players complete npc tasks (such as collection games in different chaps), cheerful sound effects can bring players sense of achievemrnt.

# **Dependencies**
Collection games #126 #166 #167 

# **Milestones**
- [ ] Understand how collection games work. (Oct. 10)
- [ ] Find the right music material. (Oct.12)
- [ ] Survey how different people feel about this sound effect. (Oct.15)
- [ ] Code implementation of cheerful sound effects. (Oct.18)

**Completion Deadline:** Oct.19

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
-Shook Jern Chung (@ShookJern) (Shook Jern Chung)
-Yu Ouyang (@YuOuyang99) (Yu Ouyang)
-Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
-Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)
