### ISSUE TITLE
Sprint 4 - Team 9 Task Ticket 1: Questionnaire user test

### ISSUE THREAD

**Issue by snakefen** [UQdeco2800/2022-ext-studio-1#202]
# **Description**
**Task:** Questionnaire user test
**Feature:** [Sprint 4 - Team 9 Feature Ticket: Improvement of Collecting Games.](#185 )

This task is mainly for the investigation of the design works and code works later. Our team needs to know the player's preference so as to carry out the follow-up work.
 
# **Dependencies**
- [x] storyline/general background  (#7 )
- [x] Sprint 4 - Team 9 Feature Ticket: Improvement of Collecting Games.(#185 )

# **Milestones**
- [ ] Make questionnaire (Oct. 16)
- [ ] Send questionnaire (Oct. 17)
- [ ] Analyze results (Oct. 18)
 
**Completion Deadline:** Oct.18
 
# **Documentation**
- [NPC Communication Play Script](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-Communication--Play-Script)
 
# **Member**
- Yufan Chen(@snakefen ) (Yufan)
