### ISSUE TITLE
Sprint 4 - Team 9 Task Ticket 2: Implement Improvements on Collection Games

### ISSUE THREAD

**Issue by snakefen** [UQdeco2800/2022-ext-studio-1#203]
# **Description**
**Task:** Implement Improvements on Collection Games
**Feature:** [Sprint 4 - Team 9 Feature Ticket: Improvement of Collecting Games.](#185 )

In the last sprint, some functions in the collection game could not be realized. After combining the data obtained from the questionnaire, we simplified some functions that could not be completed, and at the same time made the whole game more in line with the player's preference and higher degree of freedom.

# **Dependencies**
- [x] storyline/general background  (#7 )
- [x] Sprint 4 - Team 9 Feature Ticket: Improvement of Collecting Games.(#185 )

 
# **Milestones**
- [ ] Finish code requirement document (Oct. 18)
- [ ] Finish coding (Aug. 19)
- [ ] Finish unit test (Aug. 20)
 
**Completion Deadline:** Oct. 20
 
# **Documentation**
- [NPC Communication Play Script](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-Communication--Play-Script)
 
# **Member**
- Yufan Chen(@snakefen ) (Yufan)
- Junyu Zhu (@45190331) (Junyu_Zhue)
