### ISSUE TITLE
Sprint 4 - Team 7 task ticket 6: Implement the transition animation and improve the text display

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#205]
# **Description**
**Task:** [Implement the transition animation and match the select action, improve the text display](https://github.com/UQdeco2800/2022-ext-studio-1/issues/198)
**Feature:** [Improve features based on the win/lose logic and eviction menu: Goal 6](https://github.com/UQdeco2800/2022-ext-studio-1/issues/183)

In the current game, players can already experience the complete process of expelling traitors through the eviction menu, and smoothly trigger the win/lose logic associated with it. Whenever a player uses the eviction menu to select a traitor to expel, the corresponding "prompt box" will pop up to show their selection results.  However, one of the purpose of the eviction menu is to expel the traitor who caused the continent to sink, and the current interaction flow does not show this process of eviction. So in order to make the game more "juicy", it is necessary to add a transition animation to visualize the eviction process.
 
## **Example**
- **Transition animation**: When the player "clicks" the select button and confirms their choice, a transition animation will appear on the screen to connect the player's actions and the popup of the prompt box. The transition animation will show the eviction process corresponding to the NPC selected by the player (use the image of NPCs).
- **Element display**: Currently, there are many UI elements in the eviction menu. In order to ensure that the image of each UI meets the design expectations, the optimized image will be displayed (text color/position; window position/size, etc.)

# **Dependencies**
- [x] Win/lose condition for selecting the traitor (#122   ).
- [x] Design display effects of transition animations (#192     ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Integrate images corresponding to eviction process of each npc into the game. (Oct. 16)
- [ ] Step 2: Adjust the order of transition animations (There will be 4 images per eviction process). (Oct. 17)
- [ ] Step 3: Adjust the display effect, so that the transition animation can better connect the user's operation. (Oct. 17)
 
**Completion Deadline:** Oct. 17
 
# **Documentation**
- [Eviction menu](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [Storyline](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Storyline)
- [NPC information](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-info)
- [Sprint4 - Polishing-tasks: User survey (Team 7)](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Team7:User-Survery-Improve-features-based-on-the-win-lose-logic-and-eviction-menu-(-Polishing-tasks))
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)

**Comment by LIU-Evelyn** [comment]
Step1: https://github.com/UQdeco2800/2022-ext-studio-1/commit/4d3d799a0d39c11fd52da3c3251cffb6172dd3a3

**Comment by LIU-Evelyn** [comment]
Step 2: Adjusted the size and position of transition animation https://github.com/UQdeco2800/2022-ext-studio-1/commit/b0558e34876f95df9fede437254ac9f7c376a732
