### ISSUE TITLE
Sprint4 -Team5 Task Ticket: Implement lab and village scene

### ISSUE THREAD

**Issue by CodingDavid2** [UQdeco2800/2022-ext-studio-1#221]
# **Task for implement lab and village scene**
**Task:** [Implement lab and village scene](#3).
**Feature:** [https://github.com/UQdeco2800/2022-ext-studio-1/issues/184](#2)

Improve the village scenario by implementing a new lab scenario and adding a map conversion feature. The purpose of this phase is to replace the entities from the previous sprint and create new lab scenarios.

# **Dependencies**
- [ ] Change entities of village
- [ ] lab and village should change smoothly 

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Change entities of village (15/10)
- [ ] implement village scene  (18/10)
- [ ] implement the function of changing of each maps(19/10)

 
**Completion Deadline:** 19/10

 
# **Member**
- YuqiaoTong(@CodingDavid2 ) (YuqiaoTong)
