### ISSUE TITLE
Sprint 4 - Team 4: Create a pop-up window for when player pauses game

### ISSUE THREAD

**Issue by riotanabe** [UQdeco2800/2022-ext-studio-1#228]
# **Description**
**Task:** Create a pop-up window for when player pauses game.
**Feature:** Countdown Clock (#3)

When the player clicks on the pause button, aside from simply stopping the game and timer, a window should pop-up to clearly indicate that the game is paused, and to provide some options for users e.g. resume, restart. 
This task is to improve the user experience for players while playing the game. 
 
# **Dependencies**

- [ ] Design for the pop-up window needs to be created.
- [ ] Buttons should be created in the pop-up window.
- [ ] Buttons need to be designed
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design pop-up window (Oct. 13)
- [ ] Implement pop-up on pause without breaking game. Also include resume button to not prevent game functionality (Oct. 15)
- [ ] Implement additional functionality (Oct. 17)
- [ ] Implement designs for the buttons (Oct. 18)
 
**Completion Deadline:** Oct. 19

# **Member**
- Rio (@riotanabe )
- Suyang (@HAISUYANG )
- Kevin (@Kebinzzz )

**Comment by riotanabe** [comment]
Pop-up window design created in Adobe Illustrator (Design same as Player Profile window)
![pausedWindow](https://user-images.githubusercontent.com/91102176/196366165-4ac8df07-4519-40a7-a8e5-3448b9636e0f.png)

**Comment by riotanabe** [comment]
Added text button with resume functionality inside the pop-up window. Design to be completed for resume button

**Comment by riotanabe** [comment]
Resume button created by @HAISUYANG 

![Uploading resume.png…]()

**Comment by riotanabe** [comment]
Added a restart functionality + create restart button design (design created by @HAISUYANG )

![replay1](https://user-images.githubusercontent.com/91102176/196366592-31527444-ec19-4c77-a672-fa5e23e1c49d.png)
