### ISSUE TITLE
Sprint 4 - Team 9 Task Ticket 3: Graphic Design for Collecting Games

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#229]
# **Description**
**Feature:** [Sprint 4 - Team 9 Feature Ticket: Improvement of Collecting Games](#185 )

This task will mainly show the graphic requirements and design plan for the graphic drawing part.
 

# **Dependencies**
- [ ] [Pixel Grid Resolution](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Pixel-Grid-Resolution)
 
# **Milestones**
- [ ] Communicate with team members and other teams(if needed) to make sure the requirements (Oct. 13)
- [ ] Design for the graphic drawings (Oct. 17)
- [ ] Update the wiki (Oct.18)
 
**Completion Deadline:** Oct. 18

 
# **Documentation**
- [Main description of feature](../wiki/Feature)

# **Member**
- Jingyi Li (@AlynnLi) (Jingyi Li)

**Comment by AlynnLi** [comment]
The announcement board for switch game in Chap1
![电闸告示1](https://user-images.githubusercontent.com/110004991/196419885-00ac27d3-6951-4f6d-9209-be9367449398.png)

**Comment by AlynnLi** [comment]
The congratulation board for switch game in Chap1
![电闸告示2](https://user-images.githubusercontent.com/110004991/196420035-9b1f557f-3edd-4280-afb0-b58386d11985.png)

**Comment by AlynnLi** [comment]
The pale scale (as the reward)
![灰暗的鳞片](https://user-images.githubusercontent.com/110004991/196420162-b93f8830-ad53-44cf-bf77-0f65e49642e3.png)

**Comment by AlynnLi** [comment]
The announcement board for reward collection
![领奖处告示1](https://user-images.githubusercontent.com/110004991/196420997-7c4b7835-9326-4c9e-af6d-707b30bbd9d4.png)

**Comment by AlynnLi** [comment]
The congratulation board for collection pale scale in Chap2
![领奖处告示2](https://user-images.githubusercontent.com/110004991/196421196-7cb759da-4778-4746-ba00-00cec8efcf3e.png)

**Comment by AlynnLi** [comment]
The congratulation board for collecting fixed scale in Chap3
![领奖处告示3](https://user-images.githubusercontent.com/110004991/196421365-2ae780ae-a95d-40d3-bc33-1b87c358a1a4.png)

**Comment by AlynnLi** [comment]
The reward collecting place
![领奖处](https://user-images.githubusercontent.com/110004991/196421445-9af74769-efc3-49ae-8c0f-b65f4a1a8770.png)
