### ISSUE TITLE
Sprint 4 - Team 6 Task Ticket 1: Music Test

### ISSUE THREAD

**Issue by zlz8848** [UQdeco2800/2022-ext-studio-1#236]
# **Description**
**Task:** Music Test
**Feature:** [Sprint 4 - Team 6 Feature ticket 1: Sound effects when players complete npc tasks](https://github.com/UQdeco2800/2022-ext-studio-1/issues/200)

The task is to investigate how well this sound effect fits to make sure it is suitable.
 
# **Dependencies**
- [ ] Background music: [Sprint 1 - Team 3 Feature Ticket : Music](https://github.com/UQdeco2800/2022-ext-studio-1/issues/15) 

# **Milestones**
- [ ] Make questionnaire (Oct.13)
- [ ] Send questionnaire (Oct.14)
- [ ] Analyze results (Oct.15)
 
**Completion Deadline:** Oct.19
 
# **Documentation**
- [Music Test](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Music-test-(team-6))
- ...
 
# **Member**
-Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)
