### ISSUE TITLE
Sprint 4 - Team 6 Task Ticket 2: Obtaining information about clue library and implementation

### ISSUE THREAD

**Issue by ShookJern** [UQdeco2800/2022-ext-studio-1#239]
# **Description**
**Task:** [Obtaining information about clue library and implementation](#239 ).
**Feature:** [Improve clues library](#210 )

This task aims to obtain information and requirements of the clue library by communicating with team 2, and implementing it based on their needs.

# **Dependencies**

- Improvement of NPC interaction and integration with other teams’ features (mainly maps and clues) (#186 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Communicate with team 2 to obtain information about requirements (Oct. 13)
- [x] Implement code for clue library (Oct. 17)
- [x] Test new feature of clue library (Oct. 18)
 
**Completion Deadline:** Oct. 18
 
# **Documentation**
- [Fixing the clue bug](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Fixing-the-clue-bug)
 
# **Member**
-Shook Jern Chung (@ShookJern) (Shook Jern Chung)
-Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
-Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)
