### ISSUE TITLE
Sprint 1 - Team 2 Task Ticket 1: Design low/medium- fidelity prototype, with basic UI and UX

### ISSUE THREAD

**Issue by wsxmr1234** [UQdeco2800/2022-ext-studio-1#25]
# **Description**
**Task:** [Design low/medium- fidelity prototype, with basic UI and UX](#3).
**Feature:** [Achievement System](#2)

Design the layout and interaction methods of the achievement interface, draw prototypes and conduct user research, and further design according to the research results.
 
# **Dependencies**

# **Milestones**
- [ ] Conduct background research and design low-fidelity prototypes (Aug. 23)
- [ ] Conduct user surveys to get feedback (Aug. 25)
- [ ] Based on feedback, do further research, modify and finalize the prototype. (Aug. 26)
 
**Completion Deadline:** Aug. 26

 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Minrui Xu (@wsxmr1234)
- Qicheng Chen (@Wayneecc)
- Xinkai Tang (@Kai9613)
- Zihao Xia (@zihao-xia)

**Comment by wsxmr1234** [comment]
Each of our team members researched the achievement system of existing games and found some essential elements of the achievement system interface. Usually each achievement has a title and a corresponding icon, and the icon is an abstract representation of the corresponding achievement information. In addition, achievements of different categories are usually displayed in different categories in the achievement system interface of existing games. In addition to these basic elements, the achievement interface in Overwatch also displays the achievement time and achievement rewards.
![image](https://user-images.githubusercontent.com/83403258/186504121-e94aceba-abfc-4eab-81d1-3c7e4d3b900c.png)

**Comment by wsxmr1234** [comment]
The figure below is the achievement interface of Genshin Impact. Usually mobile games display the achievement information in the form of a single column because of the small screen of the mobile phone. While computer monitors are usually much larger than mobile phone screens, there is more space to display content, so double-column is the more common form. So our achievement interface is also designed in the form of two columns.
![4c13e4741ac261cdc8e1a2edb801e67](https://user-images.githubusercontent.com/83403258/186504244-fef3bf4e-76b7-4a76-af53-ffff6726fd24.jpg)

**Comment by wsxmr1234** [comment]
This is my preliminary design of the achievement interface (low-fidelity prototype). 
![achievement prototype](https://user-images.githubusercontent.com/83403258/186505247-fbeb8d1d-82fc-41ea-98db-d5688e12cdb1.JPG)

**Comment by Wayneecc** [comment]
Another style of prototype:

Each cube with dark background colour is an achievement.  Purple Eye Icon at the bottom is a "Button". When clicking this eye icon, there is a pop-ups to show the conditions for getting this achievement, or the details about this achievement.

![Screen Shot 2022-08-25 at 5 36 38 pm](https://user-images.githubusercontent.com/88493960/186604504-01f2a068-ca68-4851-8f82-db33209ac6c6.png)

![Screen Shot 2022-08-25 at 5 36 49 pm](https://user-images.githubusercontent.com/88493960/186604637-dcd01390-1b49-4d93-91cf-ec5c0d277386.png)

We also designed 'Items Collection Achievement', this achievement is displayed as a list to show users how many game items they have discovered. Clicking each item also will appear the 'Details'.
