### ISSUE TITLE
Sprint 1 - Team 1 Task Ticket: Player Character

### ISSUE THREAD

**Issue by JZ1890** [UQdeco2800/2022-ext-studio-1#29]
# **Description**
**Task:** [Player character design].
**Feature:** [Character Design](#13 )

Player character design based on the identity of the player character in the background story
 
## **Example (optional)**
- a scientist

# **Dependencies**
- [ ] Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7 

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Appearance of the player character (Aug. 19)
- [ ] moving animation (Aug. 20)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
