### ISSUE TITLE
Sprint 1 - Team 9 Task Ticket 2: Code for interaction between NPC and players

### ISSUE THREAD

**Issue by snakefen** [UQdeco2800/2022-ext-studio-1#31]
# **Description**
**Task:** Code for interaction between NPC and players.
**Feature:** [Communication with NPC](https://github.com/UQdeco2800/2022-ext-studio-1/issues/10#9)

What this code will achieve is that when the player walks to the designated unit near the npc, a dialog box will pop up in front of the player, and the pre-designed npc dialogue will appear on it. Among them, the npc dialogue will have several branches, and the player will be given different clues by choosing different options.

# **Dependencies**
- [ ] Dialogue & Clues (#10 )
- [ ] storyline/general background  (#7 )
 
# **Milestones**
- [ ] #41
- [ ] Finish the code (Aug. 29)
- [ ] Do an unit test of the code (Aug. 30)
 
**Completion Deadline:** Aug. 31
 
# **Documentation**
- [[Feature: NPC Communication Play](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Feature:-NPC-Communication---Play-Script)]

# **Member**
- Yufan Chen (@snakefen ) (Yufan Chen)
- Jingyi Li (@AlynnLi ) (Jingyi Li)
- Yifei Liu (@liu8868 ) (Yifei Liu)
- Junyu Zhu(@45190331 ) (Junyu Zhu)
