### ISSUE TITLE
Sprint 1 - Team 2 Task Ticket 2: Implement basic framework of the achievement system

### ISSUE THREAD

**Issue by zihao-xia** [UQdeco2800/2022-ext-studio-1#38]
# **Description**
**Task:** [Implement basic framework of the achievement system](#36).
**Feature:** [Sprint 1 - Team 2 Feature Ticket : Achievement System](#11 )

Implement the basic framework of the achievement system based on the prototype and UI/UX design, including the achievement system entry on the main menu, achievements interface, demo achievements, etc.

# **Dependencies**

- [ ] Sprint 1 - Team 2 Feature Ticket : Achievement System (#11 )
- [ ] Sprint 1 - Team 8 Feature Ticket: Inventory & Consumable Items (#18 )
 
# **Milestones**
- [ ] Implement basic framework (Aug. 29)
- [ ] Add demo achievements (Aug. 30)
- [ ] Do unit tests for the code (Aug. 30)
 
**Completion Deadline:** Aug. 31
 
# **Documentation**
- [Achievement](../wiki/Achievement)
 
# **Member**
- Zihao (@zihao-xia ) (Zihao Xia)
- Minrui (@wsxmr1234 ) (Minrui Xu)
- Xinkai (@Kai9613 ) (Xinkai Tang)
- Qicheng (@Wayneecc ) (Qicheng Chen)
