### ISSUE TITLE
Sprint 1 - Team 7 Feature ticket: Player Eviction Menu / GUI

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#4]
# **Description**
In the context of the game where Atlantis is about to sink, players need to find the information of the traitor who will cause the sinking of the continent through the quest, and after confirming the information, expel them from the continent to protect Atlantis. So players need an eviction menu to choose who they think is a traitor, which can also better deepen the interaction between the player and the game. After collecting some information, the player can click the player eviction menu in the game interface and select the character that he wants to expel. If the selection is correct, the game ends and the player wins; otherwise, the game will be continued.

## SubFeature/component
- **Main menu** - Displays multiple expelled characters (NPCs/characters) to be selected.
- **Selection box** - Image card for each NPC/character to be selected.
- **Information Bar** - Information or tasks that have been collected for the corresponding NPCs/characters.

## **Examples**
- **Selection box (expelling characters)**: Contains partial information on the person to be expelled, e.g. Character portrait，gender, etc.
- **Corresponding information card**: On the side of the eviction menu, the collected information about the corresponding NPC/character or completed quest will appear there.

# **Dependencies**
- Information about eviction character relies on storyline and character interactions (#Team 5: Instructions & Storyline and Team 9: Communication with NPC).
- Character selection card depends on character design (#Team 1: Character Design / Animation).

# **Milestones**
In order to implement the display part of the player eviction menu that can be used for interaction: 
- [ ] Goal 1: Determine the basic image of the eviction menu and confirm how many sub-features will be included in it, e.g. Home menu; display card; selected status etc.  (Aug. 17)
- [ ] Goal 2: Design the basic image of the eviction menu (Aug. 21)
- [ ] Goal 3: Implement the home eviction menu and integrate it into the game environment.(Aug. 25)
- [ ] Goal 4: Implement the function of selecting the expelled characters and integrate it into the game environment.(Aug. 28)
- [ ] Goal 5: User test and evaluation. (Aug. 18 - 29)

**Completion Deadline:** Aug. 30

# **Extras**
- [ ] Extra components that we may implement if we get time: Corresponding information card/bar.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Yingxin Liu (@LIU-Evelyn ) (Slack Handle)
- Shaohui Wang (@Tonywangshaohui ) (Slack Handle)
- Kexin Du (@motaA0309 ) (Slack Handle)
- Qiansen Jin (@QiansenJhin ) (Slack Handle)

**Comment by LIU-Evelyn** [comment]
@samantha-tran Hi Samantha, this is our ticket, if it has any problem, we will improve it as soon as possible :)))

**Comment by LIU-Evelyn** [comment]
Goal1: https://github.com/UQdeco2800/2022-ext-studio-1/wiki/player-eviction-menu:-User-survey-(Team-7)

**Comment by LIU-Evelyn** [comment]
Goal2: [Player-eviction-menu-sprint1](https://github.com/UQdeco2800/2022-ext-studio-1/issues/19#issuecomment-1221824302):
<img width="630" alt="Menu_background" src="https://user-images.githubusercontent.com/88132643/185842679-2a940bed-ec03-4b45-999f-4d36f6cb24a4.png">

**Comment by LIU-Evelyn** [comment]
Created a wiki page to unify the pixel resolution for studio design：
https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Pixel-Grid-Resolution
