### ISSUE TITLE
Sprint 2 - Team 8 Feature Ticket: Inventory Functionality + Item Factory Extension 

### ISSUE THREAD

**Issue by Connor-Ryan-1998** [UQdeco2800/2022-ext-studio-1#50]
# **Description**
This feature relates to refining and updating the work completed in Sprint 1 by extending the functionality of the inventroy and Item factory extension.  Looking to add a better way to consume items as well as a larger variance of implemented items for the inventroy.

A link to our sprint 1 wiki is here:
[Sprint 1](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Inventory-System-and-Consumables)

Links to our sprint 2 wiki are here:
[User Testing](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Sprint-2-Inventory-System-and-Consumables-User-Testing-(Team-8))
[Functionality](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Sprint-2-Inventory-System-and-Consumables-Functionality)

## SubFeature/component
Consumable items will be items that provide different attributes to the player or game that can only be activated a predetermined number of times before the item is lost. This feature will work to implement this functionality within the inventory system, tracking the uses of items and removing them from the player once they are used. 

## **Examples**
- Visualising the items with their png's in the inventory 
- Extending the Item Factory to be more robust and handle new items ie, clues
# **Dependencies**

# **Milestones**
- [] Designers to create a UML for desired items
- [] Display items in inventory as clickable
- [] Extend Item Factory to handle clues and consumeables 
- [] Dive suit designs 

**Completion Deadline:** End of Sprint 2

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Ty Briggs(@Tyza23 )(Ty Briggs)
- Connor Ryan (@Connor-Ryan-1998)(Connor Ryan)
- Bohan Zhao (@Bohankkk)(Bohan Zhao)
- Shiyu Liu (@11shiyu)(shiyu Liu)
- Kwong Kit Tsang (@ivantsang9723)(Kwong Kit Tsang)

**Comment by Connor-Ryan-1998** [comment]
Completed
