### ISSUE TITLE
Sprint 2 - Team 7 Feature ticket: Detailed Eviction card for NPCs

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#51]
# **Description**
In the context of the game where Atlantis is about to sink, players need to find the information of the traitor who will cause the sinking of the continent through the quest, and after confirming the information, expel them from the continent to protect Atlantis. So players need an eviction menu to choose who they think is a traitor, which can also better deepen the interaction between the player and the game. After collecting some information, the player can click the player eviction menu in the game interface and select the character that he wants to expel. If the selection is correct, the game ends and the player wins; otherwise, the game will be continued.

## SubFeature/component
- **Main menu** - Displays multiple expelled characters (NPCs/characters) to be selected.
- **Selection box** - Image card for each NPC/character to be selected.
- **Information Bar** - Information or tasks that have been collected for the corresponding NPCs/characters.

## **Examples**
- **Selection box (expelling characters)**: Contains partial information on the person to be expelled, e.g. Character portrait，gender, etc.
- **Corresponding information card**: On the side of the eviction menu, the collected information about the corresponding NPC/character or completed quest will appear there.

# **Dependencies**
- Information about eviction character relies on storyline and character interactions (#7 and  #9 ).
- Character selection card depends on character design (#13 ).

# **Milestones**
In order to implement the display part of the player eviction menu that can be used for interaction: 
- [x] Goal 1: Determine the basic image of the eviction menu and confirm how many sub-features will be included in it, e.g. Home menu; display card; selected status etc.  (Aug. 17)
- [x] Goal 2: Design the basic image of the eviction menu (Aug. 21)
- [x] Goal 3: Implement the home eviction menu and integrate it into the game environment.(Aug. 25)
- [x] Goal 4: Implement the function of selecting the expelled characters and integrate it into the game environment.(Aug. 28)
- [x] Goal 5: User test and evaluation. (Aug. 18 - 29)

**Completion Deadline:** Aug. 30

# **Extras**
- [ ] Extra components that we may implement if we get time: Corresponding information card/bar.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Shaohui Wang (@Tonywangshaohui ) (shaohui wang)
- Kexin Du (@motaA0309 ) (Kexin Du)
- Qiansen Jin (@QiansenJhin ) (Slack Handle)

**Comment by LIU-Evelyn** [comment]
The Questionnaire of user survey in sprint 2：https://docs.google.com/forms/d/e/1FAIpQLSfAnj3yslu6fuJQEVIjhoTZtxEnBaH4mGzs27GLWrxLekakoQ/viewform?usp=sf_link

**Comment by LIU-Evelyn** [comment]
Goal 2 results: #53

**Comment by LIU-Evelyn** [comment]
Completed part of feature (Goal 3): [Added the effect of the mouseover on eviction cards](https://github.com/UQdeco2800/2022-ext-studio-1/commit/7278c3559220e3eff5d642f067fee7c576b1e177)

**Comment by LIU-Evelyn** [comment]
Completed Goal 4:  Implement the information/clue windows #57

**Comment by LIU-Evelyn** [comment]
(Sep 16th) Added remaining basic NPC information and move the eviction menu into main game screen (will not restart time)
