### ISSUE TITLE
Sprint 2 - Team 7 task ticket 1: Determine the display of the information/clue window

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#52]
# **Description**
**Task:** [Determine the basic image of the information/clue window and confirm how the clues are presented](https://github.com/UQdeco2800/2022-ext-studio-1/issues/8)
**Feature:** [Basic image and sub-feature of Detailed eviction cards: Goal 1](https://github.com/UQdeco2800/2022-ext-studio-1/issues/51)

Discuss with studio members and combine questionnaires to determine the basic art style, during which our team will determine how many sub-features will be included in the initial player eviction menu based on player (other students) preferences.
 
## **Example**
- **Survey**: Aggregate questionnaire and interview data to design the interface according to the wishes of the majority of respondents
- **Determine the eviction main menu**: This is the first interface the player will see after clicking on the expulsion menu, which may contain various information about the selected character.

# **Dependencies**
- [x] Information about eviction character relies on storyline and character interactions (#7  and #9 ).
- [ ] Some image of character we will use may depends on character design (#13 ).
 
# **Milestones**
Steps that need to be completed for this task:
- [x] Step 1: Design the questionnaire and ready to use (Aug. 16)
- [x] Step 2: Aggregate questionnaire and interview data and create a document on wiki for other members of the studio to view (Aug. 17)
 
**Completion Deadline:** Aug. 17
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- ...
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
The wiki document was created to show the decision：https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu:-Detailed-Eviction-Cards-(Team-7)
