### ISSUE TITLE
Sprint 2 - Team 7 task ticket 2: Design display of the detailed eviction card and new window

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#53]
# **Description**
**Task:** [Design display effects of detailed eviction cards and information/clue windows](https://github.com/UQdeco2800/2022-ext-studio-1/issues/19)
**Feature:** [Basic image and sub-feature of Detailed eviction cards: Goal 2](https://github.com/UQdeco2800/2022-ext-studio-1/issues/51)

Based on feedback from completing goal 1, the display of detailed eviction cards has been determined through the studio. The interaction process will include two features: move mouse to cards (show the related basic information of NPC); click on cards (pop up a new window to show the related clues). Therefore, in this task, team will design the image and effect  of the menu according to this.
 
## **Example**
- **Detailed Eviction Cards**: Design the detailed interface for the eviction card, which mainly adds the Image, Name and Gender of NPCs.
- **Information/clues Windows**: Each NPC will have an eviction card (for the user to choose the traitor he considers). In order to help the player chooses the traitor more accurately, the information/clues window will popped up after he clicking the eviction card.

# **Dependencies**
- [ ] Information about eviction character relies on storyline and character interactions (#7  and #9 ).
- [ ] The basic image of NPC that shown on the cards depend on character design (#13 ).
- [x] The Player Eviction Menu (#4 ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Design draft of Detailed Eviction Card and Information/clues Window (Sep. 6)
- [ ] Step 2: Improve the final image and effect of the feature, such as adding hovering, adjusting colors, etc. (Sep. 7)
 
**Completion Deadline:** Sep. 7

### Additional goals

# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))
- [User survey for detailed eviction card](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu:-Detailed-Eviction-Cards-(Team-7))
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
In order to let the player discover the extra functions of the card, the mouseover effect of the eviction card is designed. The color of the selected card will be more vivid (highlighted) (right) than the normal card (left).
| **Normal** | **Hover**| 
| --------------- | --------------- | 
| ![evictionCard_single](https://user-images.githubusercontent.com/88132643/188372700-b60b2aab-c6fe-453f-b93e-7ef60980775e.png) | ![evictionCard_single](https://user-images.githubusercontent.com/88132643/188372700-b60b2aab-c6fe-453f-b93e-7ef60980775e.png) |

**Comment by LIU-Evelyn** [comment]
The initial idea of the information/clues window，in order to achieve the dreamy feeling of underwater elements, we set the background of the original window to be translucent：
<img width="630px" alt="information_1" src="https://user-images.githubusercontent.com/88132643/188927609-3fb03b53-9a85-4c36-80ff-22ce8bf09512.png">

**Comment by motaA0309** [comment]
September 6th: To better fit the theme of the game, some decorative elements have been replaced, such as the addition of starfish, shells, and dolphins.
| **with translucent background** | **without translucent background**| 
| --------------- | --------------- | 
| <img width="630px" alt="informationBox2" src="https://user-images.githubusercontent.com/109838814/189021237-3e8803bb-6dbd-4768-b4c0-470cf2f95bb2.png"> | <img width="630px" alt="informationBox33" src="https://user-images.githubusercontent.com/109838814/189021794-ff08e273-5f06-4dd7-a1cb-fb6ed83fa811.png"> |

**Comment by motaA0309** [comment]
September 10th: The final design image:
<img width="500px" alt="informationBoxFinal" src="https://user-images.githubusercontent.com/109838814/189458672-53249993-4b95-49ed-9cd5-6277a584e036.png">

**Comment by LIU-Evelyn** [comment]
Designed basic info about NPC:  [Design process](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Design-display-of-the-detailed-eviction-card-and-new-window#initial-idea)
