### ISSUE TITLE
Sprint 2 Team 9 Feature Ticket: NPC Communication Stage 2

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#54]
# **Description**
This feature is the improvement of the previous NPC Communication feature. This time our team is going to collaborate with Team 7 with the clue collecting codes and we will continuing writing more specific scripts for the chapter stories which Team 5 generated. In this sprint, we will trying to add selections which leads to different ends and to make implementable codes on the selections.

## SubFeature/component (optional)
1. Clue-storage coding
2. Selectable coding
3. Dialogue box
4. Chapter 2 script

# **Dependencies**

Team 5 Storyline: #7 
Team 7 Clue Storage: #52 
Team 7 Interface: #8

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Goal 1 Clue Storage Codes for Team 7
- [x] Goal 2 Interactive clickable dialogue box
- [x] Goal 3 Design & Implement of dialogue box
- [x] Goal 4 Chapter 2 script

**Completion Deadline:** Sep. 21

# **Extras (optional)**
- [x] Chapter 3 and more scripts.

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Jingyi Li (@AlynnLi) (Jingyi Li)
- Yifei Liu (@liu8868) (Yifei Liu)
- Yufan Chen (@snakefen) (Yufan)
- Junyu Zhu (@45190331) (Junyu_Zhue
