### ISSUE TITLE
Sprint 2 - Team 9 Task Ticket 1: Chapter 2 Dialogue & Clues & Dialogue Box Design

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#55]
# **Description**
**Task:** [Design of the Dialogue Box and Write the Chapter 2 Script](#9 ).
**Feature:** [Sprint 2 Team 9 Feature Ticket: NPC Communication Stage 2](#54 )

This task is mainly about the design side, we need to writing a specific Chapter script for Chapter 2 and design the dialogue box based on the style we all agreed with already.
 

# **Dependencies**
Team 5: Storyline (#7 )
Team 7: GUI Style (#8 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Chapter 2 Script with clues
- [x] Dialogue with selections that leads to different results
- [x] Dialogue Box Design
- [x] Upload wiki
- [x] Upload Dialogue Box for later implementation
- [x] If have time, do more chapter scripts & clues
 
 
# **Documentation**
- [Feature: NPC Communication Play-Script Chapter 2](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Feature:-NPC-Communication---Play-Script#chapter-2-script)
- [Dialogue Box Design](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Dialogue-Box-Design)
- ...
 
# **Member**
- Jingyi Li (@AlynnLi) (Jingyi Li)
- Yifei Liu (@liu8868) (Yifei Liu)

**Comment by AlynnLi** [comment]
Dialogue Box version 1:
![未标题-1](https://user-images.githubusercontent.com/110004991/189650113-7697f022-e426-4461-bb88-7cebd57e5d1b.png)

**Comment by AlynnLi** [comment]
Dialogue Box version 2:
![对话框2](https://user-images.githubusercontent.com/110004991/189650770-41c9fc85-a66b-444b-8dd1-db40348cd05c.png)

**Comment by AlynnLi** [comment]
Dialogue Box Ver 2 with Name Tag
![对话框2-1](https://user-images.githubusercontent.com/110004991/189681594-2687a057-6aab-4008-88ab-0aa7012cdb18.png)

**Comment by AlynnLi** [comment]
Dialogue Box Ver 1 with Name Tag
![对话框1-1](https://user-images.githubusercontent.com/110004991/189683308-2d7e1a99-19d4-49dc-866e-ce86898377c5.png)

**Comment by AlynnLi** [comment]
Final Dialogue Box with Decoration:
![对话框1-zs](https://user-images.githubusercontent.com/110004991/189888565-9432ef74-1a96-4c93-b82b-1353b37705ad.png)

**Comment by AlynnLi** [comment]
Finished ticket
