### ISSUE TITLE
Sprint 2 - Team 1 Character Design & Animation (Stage 2)

### ISSUE THREAD

**Issue by JZ1890** [UQdeco2800/2022-ext-studio-1#59]
# **Description**
In this sprint, team1 will further improve and add characters based on existing resources, and add animations to them to complete the work related to character design

## **Examples (optional)**
- **Characters and animations in the backstory
# **Dependencies**

- [x] Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline #7 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Complete the design of all NPCs (Sep. 10)
- [ ] complete all animations (Sep. 12)

**Completion Deadline:** Sep. 13

# **Extras (optional)**
- [ ] Assist other groups with Character-related functions (such as menus)

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- [Game Characters](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Game-Characters)

# **Members**
- Junwen Zhu (@JZ1890)
- Hengyuan Lu (@Awe5omeTired)
- Jialin Yu (@tgswjty)
- Yan Jiang (@whateverchris)
