### ISSUE TITLE
Sprint 2 Team 9 Task Ticket 2: Clue Storage Codes for Team 7

### ISSUE THREAD

**Issue by snakefen** [UQdeco2800/2022-ext-studio-1#61]
# **Description**
**Task:** Clue Storage Codes for Team 7
**Feature:** [Sprint 2 Team 9 Feature Ticket: NPC Communication Stage 2](#54 )

There is a concept called NPC Eviction Card, the function of this card is that when the player clicks on it, a window will pop up, showing the clues that the player has gain through communicate with the NPC.
On the basis of the previous code, add several functions and some parameters to the constructor.
When the player has passed the dialogue with the npc, we needs to add something like a list or array to store the clues obtained by the player, which is called the clue library. Then after the player uses a function called NPC Eviction Card, a window needs to be displayed to show the above clue library. At the same time, a function of getPlayerCLues is needed here. The seventh group should be able to call this function after creating an instance of player to get the clues that the player has obtained from the npc.
The npc also needs a clue library to store the clues that the npc remains. It needs a function of remove clues. After the player makes a choice, the clues that the npc currently has are reduced. At the same time, a function of getNpcCLues is needed here. The seventh group should be able to call this function by creating an instance of Npc. It need to be able to get the clues left on the current npc.
Moreover, a unit test is necessary.
 
# **Dependencies**
- [ ] storyline/general background  (#7 )
- [ ] Implement the feature: Show collected information/clues of the corresponding NPC in eviction menu(#60 )
 
# **Milestones**
- [ ] Finish code abstract (Sept. 8)
- [ ] Finish coding (Sept. 9)
- [ ] Finish unit test (Sept. 10)

**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Sprint 2 Team 9 Feature Ticket: NPC Communication Stage 2](https://github.com/UQdeco2800/2022-ext-studio-1/issues/54)]
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Richard (@AppleByter) (Richard Thomas)
- Yufan Chen(@snakefen ) (Yufan)
- Junyu Zhu(@45190331 )(DDD)
