### ISSUE TITLE
Sprint 2 - Team 2 Feature Ticket: Achievement Conditions and Display Enhancement

### ISSUE THREAD

**Issue by zihao-xia** [UQdeco2800/2022-ext-studio-1#62]
# **Description**
Implement achievement conditions and enhance the display of the achievement system interface. Realize achievement entities to make the player be able to accomplish a certain achievement. The achievement system interface will also be enhanced to become more interactive.

## SubFeature/component (optional)
- Achievement entities: make the player be able to accomplish achievements based on certain conditions
- Achievement status update: make achievement status traceable
- Achievement interface enhancement: view achievements more easily and interactively

## **Examples (optional)**
- **Accomplished an achievement**: the player collected 5 items and locked an achievement, then the locked achievement will be displayed in the achievement interface

# **Depenencies**
- Item collection status Team 8 #50 

# **Milestones**
- [x] Implement achievement entities and part of the conditions (Sep. 9)
- [x] Implement achievement status update (Sep. 11)
- [x] Enhance achievement interface display (Sep. 13)
- [x] User testing & evaluation (Sep. 13)

**Completion Deadline:** Sep. 14

# **Extras (optional)**
- [x] enhance achievement UI design

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Zihao Xia (@zihao-xia)
- Xinkai Tang (@Kai9613)
- Minrui Xu (@wsxmr1234)
- Qicheng Chen (@Wayneecc)
