### ISSUE TITLE
Sprint 2 - Team 5 Feature ticket: Detailed Storyline & instructions

### ISSUE THREAD

**Issue by ShokuJO** [UQdeco2800/2022-ext-studio-1#64]
# **Description**
Finish the rest chapters to complete the storyline, update the basic information of each npc. Add the in-game instructions page and the background of storyline and instructions.

## SubFeature/component (optional)
Stroyline: chapters, background, information of npcs, clues about traitors
Instructions: in-game content and background

## **Examples (optional)**
- **Instructions pop-up**:  A detailed page where player can view the instructions for the game(keyboard control)

# **Dependencies**
- Information about npcs (#13 ).
- Clues about traitor (#9  ).

# **Milestones**
- [ ] Finish the basic info of each npc (Sep. 9)
- [ ] Finish the chapters of stroyline(Sep. 11)
- [ ] The background design for stroyline and instructions (Sep. 12)
- [ ] In-game implementation (Sep. 14)

**Completion Deadline:** Sep. 14

# **Extras (optional)**
- [ ] Enhance in-game design 

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- JOJO (@ShokuJO) (Guanhao Qiao) 
- Qing Zhang (@Versprechen080) (Qing Zhang)
- Yuqiao Tong（@CodingDavid2）（yuqiaotong）
- Lulu Zhang (@lily441) (Lulu Zhang)

**Comment by lily441** [comment]
my surname is zhong
