### ISSUE TITLE
Sprint 2 - Team 5 task ticket: Background Design for storyline & instructions

### ISSUE THREAD

**Issue by ShokuJO** [UQdeco2800/2022-ext-studio-1#65]
# **Description**
**Task:** Backgournd design for storyline & instructions
**Feature:** [Detailed Storyline & instructions](#64 )
Because the in-game story line completed in sprint1 contains only textual content, the game will be optimized in Sprint 2 by designing the background for it.
 
# **Dependencies**
- [ ] (#64 )

 
# **Milestones**
- [ ] Design the initial background (Sep. 10)
- [ ] User test of background (Sep. 11)
- [ ] Finish the final version (Sep. 12)
 
**Completion Deadline:** Sep. 14

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Guanhao Qiao (@ShokuJO ) (Guanhao Qiao)
