### ISSUE TITLE
Sprint 1 - Tean 5 Feature ticket: Instructions & Storyline

### ISSUE THREAD

**Issue by ShokuJO** [UQdeco2800/2022-ext-studio-1#7]
# **Description**
The game's background outline is roughly that Atlantis is sinking, and players need to decipher to discover the betrayers who will lead to the silencing of Atlantis and protect it by expelling them. This requires a story line to introduce why the group appeared in Atlantis and what the motives of the betrayers are, and introduce the puzzles they need to face in each chapter. At the same time, in order to make players understand the game more quickly, we will design a game instruction interface to show players exactly how to operate.

## SubFeature/component 
-**Storyline**：Show the whole game's story background, character background, and story chapters.
-**Instructions**：A dedicated page/in-game instructions to show players how to control the game

## **Examples **
- **Storyline pop-up**: When players complete a specific task to trigger the plot, the pop-up box introducing the story will pop up
- **Instruction**: A dedicated screen to introduce the operation of the game or a label for each button at the beginning of the game

# **Dependencies**

Background of the story of the characters relies on character design(#Team 1)

# **Milestones**

- [ ] Goal 1 : finish the basic storyline and instructions which help other group to have an initial idea. (Aug. 17)
- [ ] Goal 2 : Do the first user test, based on the advice on studio to complete the storyline and instructions. (Aug. 23)
- [ ] Goal 3: Do the second user test and adjust the content of storyline. (Aug. 26)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] 

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- JOJO (@ShokuJO) (Guanhao Qiao) 
- Qing Zhang (@Versprechen080) (Qing Zhang)
- Yuqiao Tong（@CodingDavid2）（yuqiaotong）
- Lulu Zhang (@lily441) (Lulu Zhang)
- Cora (@4rco) (Chuyao Liu)

**Comment by motaA0309** [comment]
Hi guys, here is team7. Our team wants to know if specific clues have been created that allow players to identify the traitor? We might need that information to appear on the eviction menu. Sry for the bother

**Comment by motaA0309** [comment]
Hi guys, here is team7. Our team wants to know if specific clues have been created that allow players to identify the traitor? We might need that information to appear on the eviction menu. Sry for the bother #4

**Comment by motaA0309** [comment]
Hi guys, here is team7. Our team wants to know if specific clues have been created that allow players to identify the traitor? We might need that information to appear on the eviction menu. Sry for the bother #4

**Comment by motaA0309** [comment]
I do not ask about how to collect the clues. Just a few brief clues points that allow players to identify which NPC is a traitor. If not, that’s okay. We will remain this part to the next sprint. Thanks♪(･ω･)ﾉ
Bty, I will put the question on your team’s task ticket because the marking criteria requires communication between teams.
#4

**Comment by motaA0309** [comment]
I do not ask about how to collect the clues. Just about a few brief clues points that allow players to identify which NPC is a traitor. If don't have at the current stage, that’s okay. We will remain this part to the next sprint. Thanks♪(･ω･)ﾉ

**Comment by motaA0309** [comment]
I do not ask about how to collect the clues. Just about a few brief clue points that allow players to identify which NPC is a traitor. If don't have those clue points at the current stage, that’s okay. We will remain this part to the next sprint. Thanks♪(･ω･)ﾉ

**Comment by ShokuJO** [comment]
> I do not ask about how to collect the clues. Just about a few brief clue points that allow players to identify which NPC is a traitor. If don't have those clue points at the current stage, that’s okay. We will remain this part to the next sprint. Thanks♪(･ω･)ﾉ

Basically clues should be on the collected fish scales, the initial idea was specific hair/clothes/eye color, but we have not  confirmed that. We can discuss this later in the next sprint.
