### ISSUE TITLE
Sprint 1 - Team 7 task ticket 1: Determine the basic style of the eviction menu 

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#8]
# **Description**
**Task:** [Determine the basic style of the eviction menu ](#).
**Feature:** [Basic image and sub-feature of Player Eviction Menu: Goal 1](#4 )

Discuss with studio members and combine questionnaires to determine the basic art style, during which our team will determine how many sub-features will be included in the initial player eviction menu based on player (other students) preferences.
 
## **Example**
- **Survey**: Aggregate questionnaire and interview data to design the interface according to the wishes of the majority of respondents
- **Determine the eviction main menu**: This is the first interface the player will see after clicking on the expulsion menu, which may contain various information about the selected character.

# **Dependencies**
- [ ] Information about eviction character relies on storyline and character interactions (#Team 5: Instructions & Storyline and Team 9: Communication with NPC).
- [ ]Some image of character we will use may depends on character design (#Team 1: Character Design / Animation).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Design the questionnaire and ready to use (Aug. 16)
- [ ] Step 2: Aggregate questionnaire and interview data and create a document on wiki for other members of the studio to view (Aug. 17)
 
**Completion Deadline:** Aug. 17
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- ...
 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- Kexin Du (@motaA0309 ) (Kexin Du)

**Comment by LIU-Evelyn** [comment]
Google froms of eviction menu：https://docs.google.com/forms/d/e/1FAIpQLSe6KF9_wcvRrYggEqUKgB9m0GPS9glH9nOXrnNl2kaQPEG8Fg/viewform?usp=sf_link

**Comment by motaA0309** [comment]
Tencent Questionnaire (the basic style of the eviction menu) link:
https://wj.qq.com/s2/10653343/a76e/

**Comment by LIU-Evelyn** [comment]
Data analysis on the wiki：
https://github.com/UQdeco2800/2022-ext-studio-1/wiki/player-eviction-menu:-User-survey-(Team-7)
