### ISSUE TITLE
Sprint 2 - Team 5 task ticket : Design for storyline

### ISSUE THREAD

**Issue by Versprechen080** [UQdeco2800/2022-ext-studio-1#80]
# **Description**
**Task:** Design for storyline
**Feature:** [[Detailed Storyline & instructions]](https://github.com/UQdeco2800/2022-ext-studio-1/issues/74#2)

 

# **Dependencies**

- [ ] https://github.com/UQdeco2800/2022-ext-studio-1/issues/64

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design for NPCs' clues (Sep. 10)
- [ ] Design for storyline chapter 5&6 (Sep.12)
- [ ] Finish the final version (Sep.13)
 
**Completion Deadline:** Sep.14

# **Documentation**
- [Main description of feature](../wiki/Feature)
- ...
 
# **Member**
- Qing Zhang(Versprechen080) (Qing Zhang)
- Lulu Zhong (lily441) (lulu zhong)
