### ISSUE TITLE
Implement the feature: Add basic info in Eviction Card (NPC)

### ISSUE THREAD

**Issue by LIU-Evelyn** [UQdeco2800/2022-ext-studio-1#82]
# **Description**
**Task:** [Design the display of eviction card: add basic info of NPCs](https://github.com/UQdeco2800/2022-ext-studio-1/issues/57)

**Purpose**: This ticket is for effective cooperation between three groups related to basic info of NPCs
**Feature**: In the current eviction menu, there are two features that display information related to NPCs, one is the eviction card, and the other is the clue window that pops up after clicking the card. Mentioned here is a further design of the eviction card. In sprint2, Team 7 will discuss with Team 1 and Team 5, then design the display effect of basic information about NPC, and add it to the Detailed Eviction Card.
 
## **Requirement**
Players can intuitively see the basic information of the corresponding NPCs when browsing the eviction cards corresponding to different NPCs.
- **Team 7**: Will integrate and design the display effect of basic information that be added on the eviction card.
- **Team 1**: Provide the npc images that are determined to be used in sprint2.
- **Team 5**: Confirm and provide the basic information of the corresponding NPC.

# **Dependencies**
- Team 7 task ticket 3: mprove and Implement the detailed eviction card (#56    ).
- character design (#59   ) and Detailed Storyline (#64 ).
 
# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Integrate the image of NPC that will be used (Sep. 9)
- [ ] Step 2: Add the basic information to the corresponding NPC (Sep. 10)
- [ ] Step 3: Design the display effect of basic (Sep. 11)
 
**Completion Deadline:** Sep. 11
 
# **Documentation**
- [Main description of feature](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Player-Eviction-Menu-(Feature-Overviews))

 
# **Member**
- Yingxin Liu (@LIU-Evelyn ) (Yingxin LIU)
- JOJO (@ShokuJO) (Guanhao Qiao)
- Junwen Zhu (@JZ1890)

**Comment by ShokuJO** [comment]
After discussion and comparison, the final character information used in sprint2 is as follows ：
![image](https://user-images.githubusercontent.com/88018556/189523047-d2a39817-31e5-42fe-8f9f-27eb984a5c53.png)

- Nereus, female, loves opera and growing flowers
- Ares, male,have a great taste of art and poem
- Heph, male, has a propensity for violence

**Comment by JZ1890** [comment]
Hi here is team 1, after discussion we have decided to use char_4, char_5, char_6, char_7, you can find them at https://github.com/UQdeco2800/2022-ext-studio-1/tree/main/source/core/assets /images/characters, we are currently working on other characters and we will let you know when they are done

**Comment by LIU-Evelyn** [comment]
The final image of basic info card:
**Normal**

<img width="630" alt="npcMatch" src="https://user-images.githubusercontent.com/88132643/189536957-69d54479-d154-4457-be9f-93aa418c51c2.png">

**Hover**

<img width="630" alt="npcMatch_hover" src="https://user-images.githubusercontent.com/88132643/189537012-a5e19262-c830-461a-835c-6b5e82f77f5f.png">

**Comment by AlynnLi** [comment]
Hi Team 5 can you guys update the detail of the murderer's voice and body shape? I did not find any clue on your wiki so we kind of made it up by ourselves. Let us know if you guys changed it and we will update the detail. Thx!

**Comment by JZ1890** [comment]
Hi, this is team 1, there are some errors in the information provided by our member, Ares is still in production, the existing Ares avatar can be replaced with other characters, I'm sorry for this mistake. @ShokuJO @LIU-Evelyn

**Comment by ShokuJO** [comment]
After discussion with team 1, the original image of ares will be replaced with metis，and the info for Metis will be : Metis, female, Unkown. All the info have been updated on wiki [https://github.com/UQdeco2800/2022-ext-studio-1/wiki/NPC-info](NPC-info)

**Comment by ShokuJO** [comment]
We will update the clues about traitors soon! @AlynnLi

**Comment by LIU-Evelyn** [comment]
Update the info for eviction card:
<img width="370" alt="npcMetis" src="https://user-images.githubusercontent.com/88132643/189610310-6da3a74e-5739-46cd-8e53-d0a0e930c952.png">

**Comment by AlynnLi** [comment]
> We will update the clues about traitors soon! @AlynnLi

Thx!
