### ISSUE TITLE
Do Unit Test via Mocking for the countdown feature

### ISSUE THREAD

**Issue by riotanabe** [UQdeco2800/2022-ext-studio-1#84]
# **Description**
**Task:**Do Unit Test via Mocking for the countdown feature.
**Feature:** Countdown Clock (#3)

A unit test should be conducted on the countdown clock feature to ensure the component is working. The testing will occur via mocking, following the Mockito tutorial. 

# **Dependencies**

- [ ] The basic countdown should be functional (#78 )
- [ ] The use of the time buffer item should be reflected in the remaining time (#83 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] #83 should be completed (Sep 12.)
- [ ] A testing plan should be completed (Sep 12.)
 
**Completion Deadline:** Sep 13.
 
# **Documentation**
- Main description of feature https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Countdown-Timer-(Team-4)

# **Member**
- Rio Tanabe (@riotanabe ) (riotanabe)
