### ISSUE TITLE
Converting coutdownclock values to the correct format

### ISSUE THREAD

**Issue by jeffjeffUQ** [UQdeco2800/2022-ext-studio-1#88]
# **Description**
**Task:** Converting the clock values to the right format.
**Feature:** The countdown clock.

As the countdown clock values are shown in seconds right now, it would not provide the best experience to users. Under this circumstances, the clock values need to convert to the appropriate format. In this task, I will make the clock in Hours:Minute: Second format. In addition, the task needs to ensure the clock can transition correctly when it reaches some values. For instance, if the clock's current values are 00:1:00, then I need to ensure the clock can transition to 00:00:59.  
 

# **Dependencies**
- [ ] The inital version of the clock(only in seconds)

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1: Complete the logic and the implementation of the code.(Sep. 13)
- [ ] Step 2: Do some testings on the clock, for instnace, enter different time values to test the transitions.(Sep 13)

 
**Completion Deadline:** (Sep 13)

 
# **Documentation**
Main description of feature https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Countdown-Timer-(Team-4)
 
# **Member**
- Jeffrey (@jeffjeffUQ ) (Chi Heng Jeffrey Hui)
