### ISSUE TITLE
Sprint 1 - Team 9 Feature Ticket : Communication with NPC

### ISSUE THREAD

**Issue by AlynnLi** [UQdeco2800/2022-ext-studio-1#9]
# **Description**
This feature should be one of the most important feature to build up the whole game. The feature of "Communication with NPC" contains all the dialogues and how users choice would lead to different ending of the game. For working on this feature, it is important to collaborate with other teams especially with team 1 and team 5 since team 1 is working on character design and team 5 is working on the general storyline. In the general idea, the communication with NPC feature would be dialogue based. When player selects different choices of responses in the dialogue, player should gain different clues and it would lead to different endings. But for now it is mainly about working on the dialogues and clues with NPC and the choice lines lead to different endings. It would be look like the pop-up dialogue window in text games for the final product.

## SubFeature/component (optional)
The component should be mainly three parts: 
1. dialogue box design (may need to collaborate with team 1 to fit the general art style)
2. the dialogue line of different choices lead to different ending (need to collaborate with team 1, team 5, and maybe team 6 together)
3. player's choice of jumping to different ending lines by the choice making (mat need to collaborate with team 1, and also may need to implement later)

# **Dependencies**
1. dialogue box design (#team 1)
2. the dialogue line of different choices lead to different ending (#team 5 #team 1 #team 6)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Goal 1：figure out the character relationships and get some clues down (Aug. 20)
- [ ] Goal 2：finish up the first draft of different dialogue lines lead to different endings, one for win and one for lose (Aug. 23)
- [ ] Goal 3：update the fist draft of the dialogue lines, check the basic logic, make more lose conditions if possible (Aug. 26)
- [ ] Goal 4：design the dialogue box, make documents of NPC relationship with clues (Aug. 28)

**Completion Deadline:** Aug. 30

# **Extras**
- [ ] the implementation of player's choice of jumping to different ending lines by the choice making

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [User documentation](../wiki/Game-Guide#section1)
- ...

# **Members**
- Jingyi Li (@AlynnLi) (Jingyi Li)
- Yifei Liu (@liu8868) (Yifei Liu)
- Yufan Chen (@snakefen) (Yufan)
- Junyu Zhu (@45190331) (Junyu_Zhue

**Comment by AlynnLi** [comment]
Hi! Could we just @you in here in order to approve the ticket? Sorry to bother!
@samantha-tran @Amraj-Singh

**Comment by samantha-tran** [comment]
Hey! This feature ticket has been approved. 

In the description, I'd remove "For working on this feature, it is important to collaborate with other teams especially with team 1 .... the communication with NPC feature would be dialogue based. " from the description and have this information under Dependencies. 

Also, under your milestones, you could further break down Goal 4 into something like "implement player to NPC interaction into codebase" and "update Wiki page with relevant information". Just so its a little more clear!

**Comment by LIU-Evelyn** [comment]
Hi, this is team 7 :)))

we just want to ask about collecting clues, will the collected clues appear in the corresponding NPC information?

We are considering adding these clues to the NPC cards in the eviction menu in the next sprint maybe....or not.

Please reply to us if you have any ideas

**Comment by AlynnLi** [comment]
> Hi, this is team 7 :)))
> 
> we just want to ask about collecting clues, will the collected clues appear in the corresponding NPC information?
> 
> We are considering adding these clues to the NPC cards in the eviction menu in the next sprint maybe....or not.
> 
> Please reply to us if you have any ideas

Hi!!! We updated our wiki page with the complete script in task1 ticket with team5's chap1 outline, you can check that out!
