### ISSUE TITLE
Sprint 2 - Team 1 Character Animation

### ISSUE THREAD

**Issue by JZ1890** [UQdeco2800/2022-ext-studio-1#91]
# **Description**
**Task:** character animations
**Feature:** Character Design & Animation(#59 )

Animate currently identified characters for in-game use
 

# **Dependencies**

- [ ] Need team 5 help to determine character#7 
- [ ] #13 

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Identify the required characters (Sep. 10)
- [ ] complete animation (Sep. 12)
 
**Completion Deadline:** Sep. 13

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- [Game Characters](https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Game-Characters)
 
# **Member**
- Junwen Zhu (@JZ1890)
- Hengyuan Lu (@Awe5omeTired)
- Jialin Yu (@tgswjty)
- Yan Jiang (@whateverchris)
