### ISSUE TITLE
Sprint 2 - Team 6 Task Ticket 1: Lab Scene Sketch and Implementation

### ISSUE THREAD

**Issue by ShookJern** [UQdeco2800/2022-ext-studio-1#93]
# **Description**
**Task:**  [Sketching and Implementation of the lab scene] (#).
**Feature:** [Implementing lab scenario: Goal 1 & Goal 3] (#79 ) 

In this task, the lab scenario will be drafted, including all the elements present in the map. (such as the equipment in laboratories)
 
## **Example**
- Implementation of lab desks: first sketch out what the desk looks like, and then use Adobe Illustrator to render the desk pixelated.

# **Dependencies**
- Team 5: Storyline of the lab scene (#64 )
- Team 7: NPC clues and information (#54 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1: Communicate with team 5 and 7 to obtain information on elements needed. (Sept. 5-7)
- [ ] Step 2: Hold a meeting to discuss what elements will be included/ search for ideas together as a team. (Sept. 9)
- [ ] Step 3: Draw the basic sketches and styles of the elements the group discusses the map will contain. (Sept. 9-10 )
- [ ] Step 4: Use adobe illustrator to enrich the elements and make the elements into pixel style. (Sept. 10-12)
 
**Completion Deadline:** Sept. 12

# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Shook Jern Chung (@ShookJern) (Shook Jern Chung)
- Yu Ouyang (@YuOuyang99) (Yu Ouyang)
- Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
- Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)

**Comment by YuOuyang99** [comment]
After brainstorming with the group, the laboratory scene sketch is formed.
![IMG_3862F0F9C70E-1](https://user-images.githubusercontent.com/110018552/189959920-018319dd-361f-4af4-adf2-e0e34449ab0c.jpeg)

**Comment by YuOuyang99** [comment]
Elements of a lab scene. (pixel single element)
![lab element -03](https://user-images.githubusercontent.com/110018552/189978831-b5ba4e6d-46e2-4567-acdf-be93016d4b26.png)
![lab element -04](https://user-images.githubusercontent.com/110018552/189978839-989ba82d-5ded-4548-82f6-4804bb8ec301.png)
![lab element -05](https://user-images.githubusercontent.com/110018552/189978841-648a698b-dfdb-4e8e-b510-9d4868f58538.png)
![lab element -06](https://user-images.githubusercontent.com/110018552/189978846-ec83055c-1c71-4be0-9ef5-a9b78c4a174f.png)
![lab element -07](https://user-images.githubusercontent.com/110018552/189978847-5e76f861-6c59-41fd-a3b0-1a6ec9b1bc98.png)
![lab element -08](https://user-images.githubusercontent.com/110018552/189978850-2f668700-a775-47cf-ac20-bbbe9f5ff77a.png)
![lab element -09](https://user-images.githubusercontent.com/110018552/189978852-3c95dd51-aaae-4059-bedf-eacb34e20dd4.png)
![lab element -10](https://user-images.githubusercontent.com/110018552/189978854-c3fdb587-41c9-4275-b5f1-3ebfc3e489be.png)
![lab element -11](https://user-images.githubusercontent.com/110018552/189978857-f5c99066-4f4e-4e47-abde-ad797b9a389e.png)
![lab element -12](https://user-images.githubusercontent.com/110018552/189978861-3502614c-ffda-4804-895c-849d5b5b6d99.png)
![lab element -13](https://user-images.githubusercontent.com/110018552/189978862-ca45d82c-de42-46f7-8dbd-795996092ca1.png)
![lab element -14](https://user-images.githubusercontent.com/110018552/189978866-9c2e222a-bf56-475e-96d2-133122910ba6.png)
![lab element -15](https://user-images.githubusercontent.com/110018552/189978870-61099bbe-af8b-4022-8129-6438cf810a2f.png)
![lab element -16](https://user-images.githubusercontent.com/110018552/189978874-b101e6ff-a259-4aef-91e3-d045614891a5.png)
![lab element -17](https://user-images.githubusercontent.com/110018552/189978879-8df843ac-ca9d-4391-a678-552de60c87c8.png)
![lab element -18](https://user-images.githubusercontent.com/110018552/189978880-8da6e3ae-d6d3-424c-bb16-9b9c4d6fbd03.png)
![lab element -19](https://user-images.githubusercontent.com/110018552/189978882-8f358052-df03-4156-b5a1-259512925e00.png)
![lab element -20](https://user-images.githubusercontent.com/110018552/189978883-cbf7256e-c0b2-4f68-9a23-6d9ec999bed4.png)
![lab element -21](https://user-images.githubusercontent.com/110018552/189978887-a090ebe5-c0f7-4bca-aaae-f416bb1fc6cf.png)
![lab element -22](https://user-images.githubusercontent.com/110018552/189978889-1ccb8152-a84c-4f6f-af1b-b3d8e9f0ba4c.png)
![lab element -23](https://user-images.githubusercontent.com/110018552/189978894-5e1e1eb0-282f-454b-9c36-a2fe51379b6e.png)
![lab element -24](https://user-images.githubusercontent.com/110018552/189978897-8a9b691e-fa34-44d4-9400-aa21413824d1.png)
![lab element -25](https://user-images.githubusercontent.com/110018552/189978902-be8e0091-b920-4319-a1ee-bdc64f34c8dd.png)
![lab element -26](https://user-images.githubusercontent.com/110018552/189978904-cf7205a2-6f63-4965-ba41-a7091246f923.png)
![lab element -27](https://user-images.githubusercontent.com/110018552/189978909-7669152f-d000-461d-8047-9e628e0affd9.png)
![lab element -28](https://user-images.githubusercontent.com/110018552/189978912-4d5856e5-9fc4-445f-9ec2-9fe84bfc25a3.png)
![lab element -29](https://user-images.githubusercontent.com/110018552/189978914-f0cf3394-6b24-4120-ae0a-3f58ed07941f.png)
![lab element -30](https://user-images.githubusercontent.com/110018552/189978917-04a0cd17-0626-4152-b41e-2c5c9ba142f5.png)
![lab element 1](https://user-images.githubusercontent.com/110018552/189978921-633e5bf9-afd3-4e56-a5bf-cf55a5fcbbf2.png)
![lab element 02](https://user-images.githubusercontent.com/110018552/189978925-50ec909d-4350-45f8-a8ba-4aae5f3b61d5.png)
