### ISSUE TITLE
Sprint 2 - Team 6 Task Ticket 2: Improve and Implement the Exit Function

### ISSUE THREAD

**Issue by ShookJern** [UQdeco2800/2022-ext-studio-1#94]
# **Description**
**Task:** [Improve map exit function] (#3).
**Feature:** [Fixing the exit feature: Goal 2] (#79 )

This task will focus on improving and fixing the existing exit feature implemented in Sprint 1.
 
## **Example**
- Making the exit button functional, such as it will be highlighted when hovered over, and close the background map when clicked on.

# **Dependencies**
- [ ] Team 6: Map Design (#17 )

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Step 1: Deleting the exit text button/ implementing the new exit icon button (Aug. 9)
- [ ] Step 2: Improving the display of the exit icon button (effect of being hovered over/position/size etc.) (Aug. 10)
- [ ] Step 3: Pushing it to main branch (Aug. 10)
 
**Completion Deadline:** Sept. 10
 
# **Documentation**
- [Main description of feature](../wiki/Feature)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Shook Jern Chung (@ShookJern) (Shook Jern Chung)
- Yu Ouyang (@YuOuyang99) (Yu Ouyang)
- Wenji Wangkang (@WenjiWangkang) (Wenji Wangkang)
- Lingzhe Zheng (@zlz8848) (Lingzhe Zheng)
