### ISSUE TITLE
Constructing the pause and resume features for the countdown clock

### ISSUE THREAD

**Issue by jeffjeffUQ** [UQdeco2800/2022-ext-studio-1#97]
# **Description**
**Task:** [Constructing the pause and resume features for the countdown clock]
**Feature:** [Both of these tasks will contribute to the countdown clock feature]

The team believe pause and resume are important features in a game. As players may want to stop the game and come back later. Players can press pause to stop the game, which will stop the countdown clock and the main game screen. On the other hand, when players press the resume button, the game will restart, so the countdown clock and the objects in the main game screen will start moving again.
 

# **Dependencies**
- [ ]The pause and resume features will depend on the countdown clock itself.
- [ ] The pause and reume features also depend on the main game screen. 

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create the buttons (Sep. 13)
- [ ] Complete the logic to pause and resume the countdown clock(Sep. 13)
- [ ] Working on pausing and resuming objects on the main game screen(Sep. 13)
 
**Completion Deadline:** Sep. 13

 
# **Documentation**
Main description of feature https://github.com/UQdeco2800/2022-ext-studio-1/wiki/Countdown-Timer-(Team-4)
 
# **Member**
- Jeffrey (jeffjeffUQ) (Chi Heng Jeffrey Hui)
